# SPDX-License-Identifier: MIT
"""gen_vectors.py — Ed25519 cross-validation vector generator for bmc-fw crypto (E1-RUN2).

Generates `test_vectors.h` consumed by test_host.c. Uses PyCA `cryptography` as the reference
implementation (the same library ethimg.py uses to sign/verify), so this cross-validates the
in-house C verifier against the library that produces real ethimg signatures.

Usage: python3 gen_vectors.py > test_vectors.h
(Deterministic: fixed seed; commit the generated header.)
"""
from __future__ import annotations

import random
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
)

N_RANDOM = 64          # >= 64 random (key, msg, sig) triples
MAX_MSG_LEN = 512
SEED = 0xE1_20_26      # deterministic


def emit_hex(data: bytes) -> str:
    return ",".join(f"0x{b:02x}u" for b in data)


def main() -> None:
    rng = random.Random(SEED)
    print("/* SPDX-License-Identifier: MIT */")
    print("/* Auto-generated by gen_vectors.py (seed %#x). Do not edit. */" % SEED)
    print("/* Cross-validation vectors from PyCA cryptography. */")
    print("typedef struct {")
    print("    const uint8_t *pk;")
    print("    const uint8_t *msg;")
    print("    uint32_t msg_len;")
    print("    const uint8_t *sig;")
    print("    int expect; /* 1 = valid, 0 = must reject */")
    print("    const char *tag;")
    print("} kat_t;")
    print()

    entries: list[str] = []
    cases: list[str] = []

    def emit_case(pk: bytes, msg: bytes, sig: bytes, expect: int, tag: str) -> None:
        i = len(entries)
        entries.append(
            "static const uint8_t pk_%d[32] = { %s };\n"
            "static const uint8_t sig_%d[64] = { %s };\n"
            "static const uint8_t msg_%d[%d] = { %s };"
            % (i, emit_hex(pk), i, emit_hex(sig),
               i, max(len(msg), 1), emit_hex(msg) if msg else "0")
        )
        cases.append(
            '    { pk_%d, msg_%d, %du, sig_%d, %d, "%s" }'
            % (i, i, len(msg), i, expect, tag)
        )

    # Random valid + tampered vectors.
    for i in range(N_RANDOM):
        sk = Ed25519PrivateKey.generate()
        pk = sk.public_key().public_bytes_raw()
        mlen = rng.randrange(0, MAX_MSG_LEN + 1)
        msg = bytes(rng.randrange(0, 256) for _ in range(mlen))
        sig = sk.sign(msg)
        emit_case(pk, msg, sig, 1, f"rand-{i}")
        # One tamper case per vector, cycling the tamper target.
        which = i % 3
        if which == 0:  # flip a bit in the signature
            bad = bytearray(sig)
            bad[rng.randrange(0, 64)] ^= 1 << rng.randrange(0, 8)
            emit_case(pk, msg, bytes(bad), 0, f"rand-{i}-tamper-sig")
        elif which == 1:  # flip a bit in the message (or append if empty)
            if msg:
                bad = bytearray(msg)
                bad[rng.randrange(0, len(msg))] ^= 1 << rng.randrange(0, 8)
                emit_case(pk, bytes(bad), sig, 0, f"rand-{i}-tamper-msg")
            else:
                emit_case(pk, b"\x00", sig, 0, f"rand-{i}-tamper-msg")
        else:  # flip a bit in the public key
            bad = bytearray(pk)
            bad[rng.randrange(0, 32)] ^= 1 << rng.randrange(0, 8)
            emit_case(bytes(bad), msg, sig, 0, f"rand-{i}-tamper-pk")

    for e in entries:
        print(e)
        print()
    print("static const kat_t CROSS_VECTORS[] = {")
    print(",\n".join(cases))
    print("};")
    print("#define CROSS_VECTORS_LEN %d" % len(cases), file=sys.stderr)
    print("#define NUM_CROSS_VECTORS (sizeof(CROSS_VECTORS) / sizeof(CROSS_VECTORS[0]))")


if __name__ == "__main__":
    main()
