/* SPDX-License-Identifier: MIT */
/*
 * test_host.c — host-side validation harness for bmc-fw Ed25519 verify (E1-RUN2).
 *
 * Suites:
 *   1. SHA-512 KATs (FIPS 180-4 examples).
 *   2. RFC 8032 §7.1 KATs (TEST 1 empty, TEST 2, TEST 3).
 *   3. Cross-validation vectors generated by gen_vectors.py against PyCA
 *      cryptography (>= 64 random valid + tampered sig/msg/pk cases).
 *   4. Edge-case rejections: S >= L, S == L, small-order/identity A,
 *      non-canonical field encodings for A and R.
 *   5. Optional profile run (ETH_ED25519_PROFILE): fe_mul call count for the
 *      cycle-cost estimate.
 *
 * Build: gcc -Wall -Wextra -Werror -std=c99 (see crypto/Makefile).
 *
 * Plan-Ref: ethereal-plan/subsystems/S05-BMC与EMRI-mFSM.md (E1-RUN2).
 */
#include <stdio.h>
#include <string.h>

#include "ed25519.h"
#include "sha512.h"

static int g_pass;
static int g_fail;

static void check(int ok, const char *tag)
{
    if (ok) {
        g_pass++;
    } else {
        g_fail++;
        printf("FAIL: %s\n", tag);
    }
}

static int hex_eq(const uint8_t *got, const char *hex, uint32_t n)
{
    for (uint32_t i = 0; i < n; i++) {
        unsigned int v;
        if (sscanf(hex + i * 2, "%2x", &v) != 1) {
            return 0;
        }
        if (got[i] != (uint8_t)v) {
            return 0;
        }
    }
    return 1;
}

static void unhex(const char *hex, uint8_t *out, uint32_t n)
{
    for (uint32_t i = 0; i < n; i++) {
        unsigned int v = 0;
        (void)sscanf(hex + i * 2, "%2x", &v);
        out[i] = (uint8_t)v;
    }
}

/* ------------------------------------------------------------------ */
/* 1. SHA-512 KATs                                                     */
/* ------------------------------------------------------------------ */

static void test_sha512(void)
{
    uint8_t out[64];
    eth_sha512((const uint8_t *)"", 0, out);
    check(hex_eq(out,
                 "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce"
                 "47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
                 64),
          "sha512-empty");
    eth_sha512((const uint8_t *)"abc", 3, out);
    check(hex_eq(out,
                 "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a"
                 "2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f",
                 64),
          "sha512-abc");
    /* streaming across a block boundary (200 bytes, two updates) */
    {
        uint8_t buf[200];
        eth_sha512_ctx ctx;
        for (int i = 0; i < 200; i++) {
            buf[i] = (uint8_t)'a';
        }
        eth_sha512_init(&ctx);
        eth_sha512_update(&ctx, buf, 100);
        eth_sha512_update(&ctx, buf + 100, 100);
        eth_sha512_final(&ctx, out);
        check(hex_eq(out,
                     "4b11459c33f52a22ee8236782714c150a3b2c60994e9acee17fe68947a3e67"
                     "89f31e7668394592da7bef827cddca88c4e6f86e4df7ed1ae6cba71f3e98faee9f",
                     64),
              "sha512-stream-200a");
    }
}

/* ------------------------------------------------------------------ */
/* 2/3/4. Ed25519 vectors                                              */
/* ------------------------------------------------------------------ */

typedef struct {
    const char *sk;   /* unused for verify, kept for reference */
    const char *pk;
    const char *msg;  /* hex, "" for empty */
    const char *sig;
    int expect;
    const char *tag;
} rfc_t;

/* RFC 8032 §7.1 TEST 1 (empty), TEST 2 (1 byte), TEST 3 (2 bytes) */
static const rfc_t RFC_VECTORS[] = {
    {
        "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
        "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
        "",
        "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555"
        "fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b",
        1, "rfc-test1-empty",
    },
    {
        "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
        "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
        "72",
        "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da08"
        "5ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291612bb0c00",
        1, "rfc-test2",
    },
    {
        "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7",
        "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
        "af82",
        "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18"
        "ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a",
        1, "rfc-test3",
    },
};

static void run_one(const char *pk_hex, const char *msg_hex, uint32_t msg_len,
                    const char *sig_hex, int expect, const char *tag)
{
    uint8_t pk[32], sig[64], msg[1024];
    unhex(pk_hex, pk, 32);
    unhex(sig_hex, sig, 64);
    for (uint32_t i = 0; i < msg_len; i++) {
        unsigned int v = 0;
        (void)sscanf(msg_hex + i * 2, "%2x", &v);
        msg[i] = (uint8_t)v;
    }
    int got = eth_ed25519_verify(sig, pk, msg, msg_len);
    check(got == expect, tag);
    if (got != expect) {
        printf("  tag=%s expect=%d got=%d\n", tag, expect, got);
    }
}

/* group order L (LE bytes) and related constants for edge cases */
static const char *L_HEX = "edd3f55c1a631258d69cf7a2def9de1400000000000000000000000000000010";
static const char *L_PLUS1_HEX = "eed3f55c1a631258d69cf7a2def9de1400000000000000000000000000000010";

static void test_rfc_kats(void)
{
    for (size_t i = 0; i < sizeof(RFC_VECTORS) / sizeof(RFC_VECTORS[0]); i++) {
        const rfc_t *v = &RFC_VECTORS[i];
        run_one(v->pk, v->msg, (uint32_t)(strlen(v->msg) / 2), v->sig, v->expect, v->tag);
    }
    /* built-in selftest KAT */
    check(eth_ed25519_selftest() == 1, "selftest");
}

static void test_edge_cases(void)
{
    const rfc_t *base = &RFC_VECTORS[0]; /* TEST 1 as the valid baseline */
    char sig_hex[193]; /* 32-byte R hex (64) + 32-byte S hex (128) + NUL */

    /* S == L  -> reject */
    (void)snprintf(sig_hex, sizeof(sig_hex), "%.64s%s", base->sig, L_HEX);
    run_one(base->pk, base->msg, 0, sig_hex, 0, "edge-S-eq-L");
    /* S == L+1 -> reject */
    (void)snprintf(sig_hex, sizeof(sig_hex), "%.64s%s", base->sig, L_PLUS1_HEX);
    run_one(base->pk, base->msg, 0, sig_hex, 0, "edge-S-gt-L");
    /* S = 2^256-1 (all 0xff) -> reject */
    {
        uint8_t pk[32], sig[64];
        unhex(base->pk, pk, 32);
        unhex(base->sig, sig, 64);
        for (int i = 32; i < 64; i++) {
            sig[i] = 0xffu;
        }
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-S-ff");
    }
    /* A = identity encoding (01 00 ... 00) -> reject (small order) */
    {
        uint8_t pk[32] = {0}, sig[64];
        pk[0] = 0x01u;
        unhex(base->sig, sig, 64);
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-A-identity");
    }
    /* A = (0,-1): y = p-1 (ec ff .. ff 7f), order 2 -> reject (small order) */
    {
        uint8_t pk[32], sig[64];
        unhex("ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", pk, 32);
        unhex(base->sig, sig, 64);
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-A-order2");
    }
    /* A = non-canonical y == p (ed ff .. ff 7f) -> reject */
    {
        uint8_t pk[32], sig[64];
        unhex("edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", pk, 32);
        unhex(base->sig, sig, 64);
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-A-noncanon-p");
    }
    /* A = non-canonical identity (y = p+1: ee ff .. ff 7f) -> reject */
    {
        uint8_t pk[32], sig[64];
        unhex("eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", pk, 32);
        unhex(base->sig, sig, 64);
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-A-noncanon-id");
    }
    /* R = non-canonical encoding (y = p+1: ee ff .. ff 7f) -> reject */
    {
        uint8_t pk[32], sig[64];
        unhex(base->pk, pk, 32);
        unhex(base->sig, sig, 64);
        unhex("eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f", sig, 32);
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-R-noncanon");
    }
    /* R = x-sign set on x==0 encoding (y=1 with sign bit: 01 00 .. 00 | 0x80 top) -> reject */
    {
        uint8_t pk[32], sig[64];
        unhex(base->pk, pk, 32);
        unhex(base->sig, sig, 64);
        for (int i = 0; i < 32; i++) {
            sig[i] = 0;
        }
        sig[0]  = 0x01u;
        sig[31] = 0x80u; /* x==0 but sign=1: invalid encoding */
        check(eth_ed25519_verify(sig, pk, (const uint8_t *)"", 0) == 0, "edge-R-x0-sign");
    }
}

/* ------------------------------------------------------------------ */
/* cross-vectors from gen_vectors.py                                   */
/* ------------------------------------------------------------------ */

#include "test_vectors.h"

static void test_cross_vectors(void)
{
    for (size_t i = 0; i < NUM_CROSS_VECTORS; i++) {
        const kat_t *v = &CROSS_VECTORS[i];
        int got = eth_ed25519_verify(v->sig, v->pk, v->msg, v->msg_len);
        check(got == v->expect, v->tag);
        if (got != v->expect) {
            printf("  tag=%s expect=%d got=%d\n", v->tag, v->expect, got);
        }
    }
}

int main(void)
{
    test_sha512();
    test_rfc_kats();
    test_edge_cases();
    test_cross_vectors();

#ifdef ETH_ED25519_PROFILE
    {
        extern unsigned long eth_prof_fe_mul_calls;
        /* pick a valid cross-vector with a mid-size message (~64 bytes) */
        const kat_t *v = &CROSS_VECTORS[0];
        for (size_t i = 0; i < NUM_CROSS_VECTORS; i++) {
            if (CROSS_VECTORS[i].expect == 1 && CROSS_VECTORS[i].msg_len >= 48u &&
                CROSS_VECTORS[i].msg_len <= 96u) {
                v = &CROSS_VECTORS[i];
                break;
            }
        }
        eth_prof_fe_mul_calls = 0;
        int ok = eth_ed25519_verify(v->sig, v->pk, v->msg, v->msg_len);
        printf("profile: valid verify msg_len=%u ok=%d fe_mul calls=%lu\n",
               (unsigned)v->msg_len, ok, eth_prof_fe_mul_calls);
    }
#endif

    printf("host tests: %d passed, %d failed\n", g_pass, g_fail);
    if (g_fail != 0) {
        printf("RESULT: FAIL\n");
        return 1;
    }
    printf("RESULT: PASS\n");
    return 0;
}
