#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""gen_daemon_vectors.py — E1-RUN2 BMC-daemon test vectors (deterministic).

Single generator for BOTH sides of the tb_bmc_daemon contract:

  * ``--keyring``  -> ``daemon/keyring.h``: the ONE trusted Ed25519 public key
    compiled into the firmware (spec emri-v0.md sec 3.2 step 3: "v0 keyring: a
    single trusted public key compiled into the firmware").
  * ``--svh``      -> SV include for tb_bmc_daemon.sv: the image frame words
    (v0 cfg-addr-addressed format, mirroring tb_mgmt_hotswap.sv), the matching
    32-byte manifest digests, and the Ed25519 signatures over the 64-byte
    lowercase-hex UTF-8 of each digest (exactly what ethimg.py signs), plus a
    tampered-signature variant for the bad_sig negative test.

Deterministic (fixed key seed, fixed images): committed generated files are
reproducible byte-for-byte. Uses PyCA ``cryptography`` (the same library
ethimg.py signs with), so the C verifier is cross-checked against the real
signer.

Plan-Ref: ethereal-spec/control/emri-v0.md sec 3.2;
          ethereal-plan/subsystems/S05-BMC与EMRI-mFSM.md (E1-RUN2).
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

# Deterministic keypair: Ed25519 private key from a fixed-seed SHA-256 digest
# (no RNG -> byte-identical regeneration).
KEY_SEED = hashlib.sha256(b"ethereal-bmc-daemon-e1run2-testkey-v1").digest()

# Test images (v0 cfg-addr-addressed frame words, mirror tb_mgmt_hotswap.sv):
#   A: TFF on tile(0,0) eLUT4[0] -> clb_out_obs[0] toggles
#      word0 = eLUT0 TFF (tt=0x5555, ff_en, ff_rst_en, ff_rst_val=0);
#      words 8..11 = IIB mux0-3 sel=0 (v2c §7.2: feedback j=0 = clb_out[0]; v1.1 sel=18).
#   B: const1 on eLUT4[0] (tt=0xFFFF, ff_rst_val=1) -> clb_out_obs[0] constant 1.
IMG_A_WORDS = [
    0x0005555C,
    0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000,  # v2c: IIB fb j=0 = sel 0 (was v1.1 sel=18)
]
IMG_B_WORDS = [0x000FFFFE]


def _words_to_bytes(words: list[int]) -> bytes:
    return b"".join(w.to_bytes(4, "little") for w in words)


def _c_array(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}u" for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{ {body} }};"


def _sv_words(name: str, blob: bytes) -> str:
    words = [
        int.from_bytes(blob[i : i + 4], "little") for i in range(0, len(blob), 4)
    ]
    body = ", ".join(f"32'h{w:08x}" for w in words)
    n = len(words)
    return f"localparam logic [31:0] {name} [0:{n - 1}] = '{{{body}}};"


def _sv_u32_list(name: str, words: list[int]) -> str:
    body = ", ".join(f"32'h{w:08x}" for w in words)
    return f"localparam logic [31:0] {name} [0:{len(words) - 1}] = '{{{body}}};"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keyring", type=Path, help="write keyring.h (trusted pk)")
    ap.add_argument("--svh", type=Path, help="write tb_bmc_daemon SV include")
    ap.add_argument("--svh-packed", type=Path,
                    help="write tb_bmc_daemon_packed SV include")
    ap.add_argument("--frame-hex", type=Path,
                    help="packed column frame .hex (pack_tb_frames.py output; "
                         "the CRC16 tail word is dropped, DATA words kept)")
    ap.add_argument("--frame-hex-b", type=Path,
                    help="optional SECOND packed column frame (rotation stress; "
                         "emits the DAEMON_IMGP_B_* symbol set)")
    args = ap.parse_args()
    if not args.keyring and not args.svh and not args.svh_packed:
        ap.error("nothing to do: pass --keyring and/or --svh and/or --svh-packed")
    if args.svh_packed and not args.frame_hex:
        ap.error("--svh-packed requires --frame-hex <path>")

    sk = Ed25519PrivateKey.from_private_bytes(KEY_SEED)
    pk = sk.public_key().public_bytes_raw()

    dig_a = hashlib.sha256(_words_to_bytes(IMG_A_WORDS)).digest()
    dig_b = hashlib.sha256(_words_to_bytes(IMG_B_WORDS)).digest()
    # ethimg signs the 64-byte lowercase-hex UTF-8 of the digest (sec 3.2 step 3).
    sig_a = sk.sign(dig_a.hex().encode("utf-8"))
    sig_b = sk.sign(dig_b.hex().encode("utf-8"))
    tam_a = bytes([sig_a[0] ^ 0x01]) + sig_a[1:]

    if args.keyring:
        args.keyring.parent.mkdir(parents=True, exist_ok=True)
        args.keyring.write_text(
            "/* SPDX-License-Identifier: MIT */\n"
            "/*\n"
            " * keyring.h — E1-RUN2 trusted Ed25519 public key (v0 keyring).\n"
            " *\n"
            " * AUTO-GENERATED by gen_daemon_vectors.py (deterministic fixed-seed\n"
            " * key; reproducible byte-for-byte). Do not edit — regenerate.\n"
            " * Real key management (fuse/ROM/bundled) is E2-SEC1 territory\n"
            " * (spec emri-v0.md sec 9 item 4).\n"
            " *\n"
            " * Plan-Ref: ethereal-spec/control/emri-v0.md sec 3.2 step 3.\n"
            " */\n"
            "#ifndef BMC_FW_DAEMON_KEYRING_H\n"
            "#define BMC_FW_DAEMON_KEYRING_H\n"
            "\n"
            "#include <stdint.h>\n"
            "\n"
            "/* The single trusted Ed25519 public key (raw 32 bytes, RFC 8032). */\n"
            + _c_array("ETH_TRUSTED_PK", pk)
            + "\n\n#endif /* BMC_FW_DAEMON_KEYRING_H */\n"
        )
        print(f"[gen_daemon_vectors] keyring.h: trusted pk = {pk.hex()}")

    if args.svh_packed:
        # Packed single-column image (emri-v0.md sec 3.3): the frame file is
        # DATA words + one CRC16 tail word; the OCC/host transports DATA words
        # only (the tail is a transport trailer), so the digest covers the
        # DATA words (little-endian in-word, ascending word order).
        def _packed(path: Path) -> tuple[list[int], bytes, bytes]:
            """(DATA words, digest, signature) for one packed column frame."""
            ls = [ln.strip() for ln in path.read_text().splitlines() if ln.strip()]
            ws = [int(ln, 16) & 0xFFFFFFFF for ln in ls][:-1]
            dg = hashlib.sha256(_words_to_bytes(ws)).digest()
            return ws, dg, sk.sign(dg.hex().encode("utf-8"))

        img_p, dig_p, sig_p = _packed(args.frame_hex)
        tam_p = bytes([sig_p[0] ^ 0x01]) + sig_p[1:]
        args.svh_packed.parent.mkdir(parents=True, exist_ok=True)
        text = (
            "// AUTO-GENERATED by gen_daemon_vectors.py (deterministic). Do not edit.\n"
            "// tb_bmc_daemon_packed host-write vectors: PACKED column image DATA\n"
            "// words (frame_map format, CRC16 tail excluded) + manifest digest +\n"
            "// Ed25519 signature over hex-UTF-8(digest) + tampered variant.\n"
            "// emri-v0.md sec 3.3 (run_packed).\n"
            f"localparam int DAEMON_IMGP_NWORDS = {len(img_p)};\n"
            + _sv_u32_list("DAEMON_IMGP_WORDS", img_p)
            + "\n"
            + _sv_words("DAEMON_IMGP_DIGEST", dig_p)
            + "\n"
            + _sv_words("DAEMON_IMGP_SIG", sig_p)
            + "\n"
            + _sv_words("DAEMON_IMGP_SIG_TAMPER", tam_p)
            + "\n"
        )
        if args.frame_hex_b is not None:
            img_q, dig_q, sig_q = _packed(args.frame_hex_b)
            text += (
                "// Second signed image (rotation-stress TB, same convention).\n"
                f"localparam int DAEMON_IMGP_B_NWORDS = {len(img_q)};\n"
                + _sv_u32_list("DAEMON_IMGP_B_WORDS", img_q)
                + "\n"
                + _sv_words("DAEMON_IMGP_B_DIGEST", dig_q)
                + "\n"
                + _sv_words("DAEMON_IMGP_B_SIG", sig_q)
                + "\n"
            )
            print(f"[gen_daemon_vectors] svh-packed B: {len(img_q)} DATA words, "
                  f"digest_PB={dig_q.hex()}")
        args.svh_packed.write_text(text)
        print(f"[gen_daemon_vectors] svh-packed: {len(img_p)} DATA words, "
              f"digest_P={dig_p.hex()}")

    if args.svh:
        args.svh.parent.mkdir(parents=True, exist_ok=True)
        args.svh.write_text(
            "// AUTO-GENERATED by gen_daemon_vectors.py (deterministic). Do not edit.\n"
            "// tb_bmc_daemon host-write vectors: image words + manifest digests +\n"
            "// Ed25519 signatures over hex-UTF-8(digest) (ethimg convention) +\n"
            "// one tampered-signature variant. emri-v0.md sec 3.2.\n"
            f"localparam int DAEMON_IMG_A_NWORDS = {len(IMG_A_WORDS)};\n"
            + _sv_u32_list("DAEMON_IMG_A_WORDS", IMG_A_WORDS)
            + "\n"
            f"localparam int DAEMON_IMG_B_NWORDS = {len(IMG_B_WORDS)};\n"
            + _sv_u32_list("DAEMON_IMG_B_WORDS", IMG_B_WORDS)
            + "\n"
            + _sv_words("DAEMON_IMG_A_DIGEST", dig_a)
            + "\n"
            + _sv_words("DAEMON_IMG_A_SIG", sig_a)
            + "\n"
            + _sv_words("DAEMON_IMG_A_SIG_TAMPER", tam_a)
            + "\n"
            + _sv_words("DAEMON_IMG_B_DIGEST", dig_b)
            + "\n"
            + _sv_words("DAEMON_IMG_B_SIG", sig_b)
            + "\n"
        )
        print(f"[gen_daemon_vectors] svh: digest_A={dig_a.hex()}")
        print(f"[gen_daemon_vectors] svh: digest_B={dig_b.hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
