/* SPDX-License-Identifier: MIT */
/*
 * keyring.h — E1-RUN2 trusted Ed25519 public key (v0 keyring).
 *
 * AUTO-GENERATED by gen_daemon_vectors.py (deterministic fixed-seed
 * key; reproducible byte-for-byte). Do not edit — regenerate.
 * Real key management (fuse/ROM/bundled) is E2-SEC1 territory
 * (spec emri-v0.md sec 9 item 4).
 *
 * Plan-Ref: ethereal-spec/control/emri-v0.md sec 3.2 step 3.
 */
#ifndef BMC_FW_DAEMON_KEYRING_H
#define BMC_FW_DAEMON_KEYRING_H

#include <stdint.h>

/* The single trusted Ed25519 public key (raw 32 bytes, RFC 8032). */
static const uint8_t ETH_TRUSTED_PK[32] = { 0xcbu, 0xa3u, 0x3au, 0xadu, 0x2cu, 0x0bu, 0xedu, 0xe3u, 0x3bu, 0x18u, 0xefu, 0xfdu, 0x55u, 0x26u, 0xe7u, 0xcbu, 0xb1u, 0x2bu, 0x92u, 0x29u, 0x81u, 0x98u, 0x70u, 0x34u, 0x90u, 0xeau, 0x23u, 0x6bu, 0x21u, 0x02u, 0xceu, 0x98u };

#endif /* BMC_FW_DAEMON_KEYRING_H */
