`default_nettype none
// SPDX-License-Identifier: MIT
// Module:      tb_npu_tinyml
// Description: End-to-end TinyML inference on the NPU-Tiny tile (E3-SVC1): a
//              two-layer INT8 MLP whose every intermediate is checked against the
//              Python golden model (KWS-shaped demo, C11 §5 "KWS 级负载").
// Details:     Layer 1 is a K=16 GEMM run as two chunks inside ONE session: the
//              first chunk is x*W1 and the second folds the bias (A=[1,0,...],
//              W row 0 = b1) with CTRL.ACC_EN=1, so the tile — not the host —
//              adds the bias. The host then applies the model's activation
//              quantization  q = clamp((relu(acc)+128) >>> 8, -128, 127)  and the
//              TB checks the resulting INT8 vector against the vector file before
//              feeding it to layer 2 (K=8, 4 classes). The class is the argmax of
//              the first four layer-2 outputs; the vector file pins both the
//              per-layer C buffers and the class, all generated by
//              tests/npu/gen_npu_vectors.py from tests/npu/npu_model.py.
//              Data is a fixed LCG seed, so the demo is bit-reproducible.
// Maintainer:  BaiTian6641
// Created:     2026-09-13
// Tags:        RTL, TESTBENCH
// Plan-Ref:    ethereal-plan/subsystems/S11-Service-Tile.md §2.2 §4 ·
//              ethereal-plan/components/C11-NPU-Tiny组件.md §3.1 §5
`timescale 1ns/1ps

module tb_npu_tinyml;
    localparam logic [7:0] CSR_CTRL   = 8'h00;
    localparam logic [7:0] CSR_DESC   = 8'h08;
    localparam logic [7:0] CSR_SESSID = 8'h0C;
    localparam logic [7:0] CSR_AWR    = 8'h10;
    localparam logic [7:0] CSR_WWR    = 8'h14;
    localparam logic [7:0] CSR_CADDR  = 8'h20;
    localparam logic [7:0] CSR_CRD    = 8'h24;

    localparam string VEC = "ethereal-fabric/tests/npu/vectors/npu_tinyml.txt";
    localparam integer NCLS = 4;

    logic clk = 1'b0;
    always #5 clk = ~clk;

    logic         rst_ni = 1'b1;
    logic         sess_rst;
    logic         csr_we, csr_re;
    logic [7:0]   csr_addr;
    logic [31:0]  csr_wdata;
    logic [31:0]  csr_rdata;
    logic         irq;
    logic [2047:0] obs_acc;
    logic [511:0]  obs_wgt, obs_wstg, obs_feed;
    logic [2047:0] obs_cbuf;
    logic [79:0]   obs_ctl;

    npu_t dut (
        .clk_i(clk), .rst_ni(rst_ni), .sess_rst_i(sess_rst),
        .csr_we_i(csr_we), .csr_re_i(csr_re), .csr_addr_i(csr_addr),
        .csr_wdata_i(csr_wdata), .csr_rdata_o(csr_rdata), .irq_o(irq),
        .obs_acc_o(obs_acc), .obs_wgt_o(obs_wgt), .obs_wstg_o(obs_wstg),
        .obs_feed_o(obs_feed), .obs_cbuf_o(obs_cbuf), .obs_ctl_o(obs_ctl)
    );

    integer errors;
    integer fd;
    logic [31:0] y1 [0:7];          // layer-1 accumulator row
    logic [31:0] crow [0:7];        // last-read C row 0
    logic [7:0]  q1 [0:7];          // host requantized activation
    logic [31:0] y2 [0:7];          // layer-2 accumulator row
    integer cls_got, cls_exp;
    integer cyc_l1, cyc_l2;
    logic [31:0] c_exp [0:63];

    task csr_write(input [7:0] a, input [31:0] d);
        begin
            @(negedge clk);
            csr_addr  = a;
            csr_wdata = d;
            csr_we    = 1'b1;
            csr_re    = 1'b0;
            @(negedge clk);
            csr_we    = 1'b0;
        end
    endtask

    task csr_read(input [7:0] a, output [31:0] d);
        begin
            @(negedge clk);
            csr_addr = a;
            csr_we   = 1'b0;
            csr_re   = 1'b1;
            #1 d = csr_rdata;
            @(negedge clk);
            csr_re = 1'b0;
        end
    endtask

    function integer rd_hex;
        input integer f;
        integer v;
        begin
            v = 0;
            if ($fscanf(f, "%h", v) != 1) begin
                $display("FAIL: vector file ended early");
                errors = errors + 1;
            end
            rd_hex = v & 32'h000000FF;
        end
    endfunction

    function integer rd_hex32;
        input integer f;
        integer v;
        begin
            v = 0;
            if ($fscanf(f, "%h", v) != 1) begin
                $display("FAIL: vector file ended early");
                errors = errors + 1;
            end
            rd_hex32 = v;
        end
    endfunction

    // Read A (M=1 -> 8 bytes as 2 words) from the vector stream.
    task load_a1(input integer f);
        integer b0, b1, b2, b3;
        begin
            b0 = rd_hex(f); b1 = rd_hex(f); b2 = rd_hex(f); b3 = rd_hex(f);
            csr_write(CSR_AWR, {b3[7:0], b2[7:0], b1[7:0], b0[7:0]});
            b0 = rd_hex(f); b1 = rd_hex(f); b2 = rd_hex(f); b3 = rd_hex(f);
            csr_write(CSR_AWR, {b3[7:0], b2[7:0], b1[7:0], b0[7:0]});
        end
    endtask

    // Write A from the TB's own INT8 vector (the requantized activation q1).
    task write_a_vec;
        begin
            csr_write(CSR_AWR, {q1[3], q1[2], q1[1], q1[0]});
            csr_write(CSR_AWR, {q1[7], q1[6], q1[5], q1[4]});
        end
    endtask

    task load_w(input integer f);
        integer i, b0, b1, b2, b3;
        begin
            for (i = 0; i < 16; i = i + 1) begin
                b0 = rd_hex(f); b1 = rd_hex(f); b2 = rd_hex(f); b3 = rd_hex(f);
                csr_write(CSR_WWR, {b3[7:0], b2[7:0], b1[7:0], b0[7:0]});
            end
        end
    endtask

    // Read the whole C buffer; row 0 lands in crow[]. With compare=1 the 64 golden
    // words are also consumed from the vector stream (and compared).
    task read_c_row(input integer f, input integer compare);
        integer i;
        logic [31:0] got;
        begin
            csr_write(CSR_CADDR, 32'h0);
            for (i = 0; i < 64; i = i + 1) begin
                if (compare) c_exp[i] = rd_hex32(f);
                csr_read(CSR_CRD, got);
                if (i < 8) crow[i] = got;               // row 0 = the M=1 result
                if (compare && (got !== c_exp[i])) begin
                    errors = errors + 1;
                    $display("FAIL: C[%0d] = %08x, golden %08x", i, got, c_exp[i]);
                end
                if ((i >= 8) && (got !== 32'h0)) begin
                    errors = errors + 1;
                    $display("FAIL: C[%0d] (row %0d) = %08x, must stay blank (M=1)", i, i / 8, got);
                end
            end
        end
    endtask

    task start_run(input integer acc_en, output integer cycles);
        integer n;
        logic [31:0] cyc;
        begin
            csr_write(CSR_CTRL, {28'h0, acc_en[0], 1'b0, 1'b0, 1'b1});
            n = 0;
            while ((obs_ctl[3] !== 1'b1) && (n < 20)) begin @(negedge clk); n = n + 1; end
            if (n >= 20) begin
                errors = errors + 1;
                $display("FAIL: START not accepted (desc_err=%b)", obs_ctl[7]);
            end
            n = 0;
            while ((obs_ctl[4] !== 1'b1) && (n < 400)) begin @(negedge clk); n = n + 1; end
            if (n >= 400) begin
                errors = errors + 1;
                $display("FAIL: DONE timeout");
            end
            csr_read(8'h28, cyc);                        // CYC_CNT
            cycles = cyc;
        end
    endtask

    integer i, tot_cyc;
    initial begin
        errors  = 0;
        tot_cyc = 0;
        sess_rst = 1'b0;
        csr_we   = 1'b0;
        csr_re   = 1'b0;
        csr_addr = 8'h00;
        csr_wdata = 32'h0;
        for (i = 0; i < 8; i = i + 1) begin
            y1[i] = 32'h0; y2[i] = 32'h0; q1[i] = 8'h0;
        end

        @(negedge clk); rst_ni = 1'b0;
        repeat (3) @(negedge clk); rst_ni = 1'b1;
        repeat (2) @(negedge clk);

        fd = $fopen(VEC, "r");
        if (fd == 0) begin
            $display("FAIL: cannot open %s", VEC);
            $finish;
        end

        // ---------------- layer 1, chunk 0: x * W1 ----------------
        csr_write(CSR_SESSID, 32'd1);
        repeat (4) @(negedge clk);
        csr_write(CSR_DESC, {8'h00, 8'd8, 8'd8, 8'd1});     // M=1, K=8/chunk, N=8
        load_a1(fd);
        load_w(fd);
        start_run(0, cyc_l1);
        read_c_row(fd, 0);                                  // no golden compare yet
        for (i = 0; i < 8; i = i + 1) y1[i] = crow[i];
        $display("  layer 1 chunk 0 (x*W1) done: C[0]=%0d in %0d cycles", y1[0], cyc_l1);

        // ---------------- layer 1, chunk 1: bias fold (ACC_EN) ----------------
        load_a1(fd);
        load_w(fd);
        start_run(1, cyc_l1);
        read_c_row(fd, 1);                                  // compare the accumulated C
        for (i = 0; i < 8; i = i + 1) y1[i] = crow[i];
        tot_cyc = tot_cyc + cyc_l1;
        $display("  layer 1 chunk 1 (bias, ACC_EN) done: y1 = %0d %0d %0d %0d %0d %0d %0d %0d (%0d cycles)",
                 y1[0], y1[1], y1[2], y1[3], y1[4], y1[5], y1[6], y1[7], cyc_l1);

        // ---------------- host activation: ReLU + requant to INT8 ----------------
        for (i = 0; i < 8; i = i + 1) begin
            integer acc_s;
            integer q;
            integer q_exp;
            acc_s = y1[i];
            if (acc_s < 0) acc_s = 0;                       // ReLU
            q = (acc_s + 128) >>> 8;                        // model requant_i8
            if (q > 127) q = 127;
            if (q < -128) q = -128;
            q1[i] = q[7:0];
            q_exp = rd_hex(fd);
            if (q1[i] !== q_exp[7:0]) begin                 // compare to golden Q1
                errors = errors + 1;
                $display("FAIL: requantized activation q1[%0d] = %0d, golden %0d",
                         i, q1[i], q_exp[7:0]);
            end
        end

        // ---------------- layer 2: q1 * W2 ----------------
        csr_write(CSR_SESSID, 32'd2);
        repeat (4) @(negedge clk);
        csr_write(CSR_DESC, {8'h00, 8'd8, 8'd8, 8'd1});
        write_a_vec;
        load_w(fd);
        start_run(0, cyc_l2);
        read_c_row(fd, 1);
        for (i = 0; i < 8; i = i + 1) y2[i] = crow[i];
        tot_cyc = tot_cyc + cyc_l2;
        $display("  layer 2 (q1*W2) done: y2 = %0d %0d %0d %0d (%0d %0d %0d %0d) in %0d cycles",
                 y2[0], y2[1], y2[2], y2[3], y2[4], y2[5], y2[6], y2[7], cyc_l2);

        // ---------------- classification ----------------
        cls_exp = rd_hex(fd);
        cls_got = 0;
        for (i = 1; i < NCLS; i = i + 1) begin
            if ($signed(y2[i]) > $signed(y2[cls_got])) cls_got = i;
        end
        if (cls_got !== cls_exp) begin
            errors = errors + 1;
            $display("FAIL: class = %0d, golden %0d", cls_got, cls_exp);
        end
        $display("----------------------------------------------------------------");
        $display("tb_npu_tinyml: 2-layer INT8 MLP on the tile, %0d tile cycles for 2 layers", tot_cyc);
        $display("tb_npu_tinyml: inference result = class %0d (golden %0d)", cls_got, cls_exp);
        if (errors == 0) $display("TEST PASSED: TinyML inference bit-exact vs golden model");
        else             $display("TEST FAILED: %0d error(s)", errors);
        $finish;
    end

    initial begin
        #2000000;
        $display("FAIL: watchdog timeout");
        $finish;
    end
endmodule

`default_nettype wire
