# SPDX-License-Identifier: MIT
"""pytest for the heterogeneous bitgen (Stage 5b): bitgen_db hard-cell capture
+ bitgen_het vbus-ctrl config mapping.

THE acceptance (``test_dsp_config_computes``): build the LEVEL-1 DB on the MAC
circuit's VPR pack/place (W=48), map the captured MaccCell to a dsp_tile_type
vbus-ctrl config with host operands 7*6, generate a SystemVerilog TB that drives
the REAL dsp_t RTL with those bitgen-produced values, run it under iverilog, and
assert ``vp_o == 42``. This proves the bitgen -> tile-config path end-to-end.
"""
from __future__ import annotations

import os
import shutil
import subprocess

import pytest

from bitgen_db import build_db
from bitgen_het import het_tiles_to_config, macc_to_dsp_config, mem_to_mem_config

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
MAPPER = os.path.join(REPO, "generated", "mapper")
RTL_TILE = os.path.join(REPO, "ethereal-fabric", "rtl", "tile")
RTL_INF = os.path.join(REPO, "ethereal-fabric", "rtl", "inf")

NET = os.path.join(MAPPER, "mac_circuit_w48_mac_circuit.net")
PLACE = os.path.join(MAPPER, "mac_circuit_w48_mac_circuit.place")
BLIF = os.path.join(MAPPER, "mac_circuit.blif")

IVERILOG = shutil.which("iverilog") and shutil.which("vvp")

pytestmark = pytest.mark.skipif(
    not (os.path.exists(NET) and os.path.exists(PLACE) and os.path.exists(BLIF)),
    reason="MAC circuit VPR outputs (W=48) not generated")


# =============================================================================
# DB capture
# =============================================================================

def test_mac_db_captures_macc():
    db = build_db(NET, PLACE, BLIF)
    assert len(db.macc_cells) == 1, f"expected 1 MaccCell, got {len(db.macc_cells)}"
    cell = next(iter(db.macc_cells.values()))
    # .place: m[0] is the only mult_27x18 block; coord must match the DB key.
    assert cell.tile in db.macc_cells
    assert db.macc_cells[cell.tile] is cell
    # Bit-blasted operand nets, order-preserved (a[0]=bit0).
    assert cell.a_nets == [f"a[{i}]" for i in range(27)]
    assert cell.b_nets == [f"b[{i}]" for i in range(18)]
    # Leaf Y port lists the output nets m[0..47].
    assert cell.y_nets == [f"m[{i}]" for i in range(48)]


# =============================================================================
# macc -> dsp config
# =============================================================================

def test_macc_to_dsp_config():
    db = build_db(NET, PLACE, BLIF)
    cell = next(iter(db.macc_cells.values()))
    cfg = macc_to_dsp_config(cell, acc=False, lat_sel=3, aval=7, bval=6, cval=0)
    assert cfg["dsp_va"] == 7
    assert cfg["dsp_vb"] == 6
    assert cfg["dsp_ven"] == 1
    assert cfg["dsp_vcasc"] == 0
    # mode = acc(0) | lat_sel(3)<<1 = 0b110 = 6
    assert cfg["dsp_mode"] == (0 | (3 << 1))
    assert cfg["dsp_mode"] & 1 == 0            # acc=0 (MULT)
    assert (cfg["dsp_mode"] >> 1) & 0x3 == 3   # lat_sel=3


def test_het_tiles_to_config_keys_by_tile():
    db = build_db(NET, PLACE, BLIF)
    tile = next(iter(db.macc_cells))
    out = het_tiles_to_config(db,
                              dsp_operands={tile: (7, 6, 0)},
                              dsp_mode={tile: (False, 3)})
    assert tile in out
    assert out[tile]["dsp_va"] == 7
    assert out[tile]["dsp_vb"] == 6


# =============================================================================
# mem cell (ROM-preload path)
# =============================================================================

def test_mem_cell_config_rom_preload():
    # A synthetic MemCell (a RAM circuit's .net capture is a Stage-6 add); the
    # ROM-preload mapping is exercised directly.
    from bitgen_db import MemCell
    cell = MemCell(addr_nets=[f"a[{i}]" for i in range(11)],
                   data_in_nets=[f"d[{i}]" for i in range(32)],
                   we_net="we",
                   data_out_nets=[f"q[{i}]" for i in range(32)],
                   tile=(2, 3))
    cfg = mem_to_mem_config(cell, init={5: 0xDEADBEEF})
    assert cfg["mem_mode"] == 0
    # vbus-ctrl: va=5@[13:0], ven@16, vwe=1111@18
    assert (cfg["mem_vbus_ctrl"] & 0x3FFF) == 5
    assert (cfg["mem_vbus_ctrl"] >> 16) & 1 == 1
    assert (cfg["mem_vbus_ctrl"] >> 18) & 0xF == 0xF
    assert cfg["mem_vd_i"] == 0xDEADBEEF


# =============================================================================
# THE acceptance: bitgen-produced dsp config -> dsp_t RTL computes 7*6 = 42
# =============================================================================

_TB_TEMPLATE = """`default_nettype none
`timescale 1ns/1ps
// AUTO-GENERATED by test_bitgen_het.test_dsp_config_computes (Stage 5b).
// Drives the real dsp_t RTL with the BITGEN-PRODUCED vbus-ctrl config.
module tb_bitgen_het;
    logic clk = 1'b0;
    always #5 clk = ~clk;
    logic rst_ni, cfg_we;
    logic [23:0] cfg_data;
    logic ven;
    logic signed [26:0] va;
    logic signed [17:0] vb;
    logic signed [47:0] vcasc, vp;
    dsp_t u_dsp (
        .clk_i(clk), .rst_ni(rst_ni), .ven_i(ven),
        .va_i(va), .vb_i(vb), .vcasc_i(vcasc), .vp_o(vp),
        .cfg_we_i(cfg_we), .cfg_data_i(cfg_data)
    );
    integer errors;
    initial begin
        errors = 0;
        rst_ni = 1'b1; cfg_we = 1'b0; cfg_data = '0;
        ven = 1'b0; va = '0; vb = '0; vcasc = '0;
        @(negedge clk); rst_ni = 1'b0; @(negedge clk); @(negedge clk); rst_ni = 1'b1;
        // 1. config write: mode word (acc / lat_sel) — the bitgen dsp_mode.
        @(negedge clk); cfg_data = 24'h{mode:06x}; cfg_we = 1'b1;
        @(negedge clk); cfg_we = 1'b0;
        // 2. drive the bitgen operand values (va/vb/vcasc) + enable.
        @(negedge clk); va = 27'sd{aval}; vb = 18'sd{bval}; vcasc = 48'sd{cval}; ven = 1'b1;
        // 3. flush the pipeline (lat_sel={lat} -> wait enough cycles).
        repeat (5) @(negedge clk);
        if (vp !== 48'sd{expect}) begin
            errors = errors + 1;
            $display("FAIL: dsp_t vp=%0d want %0d", vp, {expect});
        end else $display("  bitgen cfg -> dsp_t vp=%0d OK", vp);
        if (errors == 0) $display("TEST PASSED");
        else             $display("TEST FAILED: %0d errors", errors);
        $finish;
    end
endmodule
`default_nettype wire
"""


@pytest.mark.skipif(not IVERILOG, reason="iverilog/vvp not on PATH")
def test_dsp_config_computes(tmp_path):
    db = build_db(NET, PLACE, BLIF)
    cell = next(iter(db.macc_cells.values()))
    # host-driven constant operands 7*6 (Stage-5b model), MULT, lat_sel=3.
    cfg = macc_to_dsp_config(cell, acc=False, lat_sel=3, aval=7, bval=6, cval=0)
    assert cfg["dsp_va"] == 7 and cfg["dsp_vb"] == 6
    tb = _TB_TEMPLATE.format(mode=cfg["dsp_mode"], aval=cfg["dsp_va"],
                             bval=cfg["dsp_vb"], cval=cfg["dsp_vcasc"],
                             lat=(cfg["dsp_mode"] >> 1) & 0x3, expect=42)
    tb_path = tmp_path / "tb_bitgen_het.sv"
    tb_path.write_text(tb, encoding="utf-8")
    out = tmp_path / "tb_bitgen_het.vvp"
    srcs = [os.path.join(RTL_INF, "eth_inf_dsp_mac.sv"),
            os.path.join(RTL_TILE, "dsp_t.sv"),
            str(tb_path)]
    subprocess.run(["iverilog", "-g2012", "-o", str(out),
                    f"-I{RTL_INF}", *srcs], check=True)
    res = subprocess.run(["vvp", str(out)], check=True,
                         capture_output=True, text=True)
    assert "TEST PASSED" in res.stdout, res.stdout + res.stderr
