`default_nettype none
// SPDX-License-Identifier: CERN-OHL-S-2.0
// Module:      eth_rv_boot_rom
// Description: The eth_rv BootROM — the 4 KiB read-only region at 0x0000_1000 the
//              core starts executing from after reset (E2-RV2 increment 5, S3).
// Details:     WHY A ROM AND NOT "START AT DRAM": the firmware handoff contract
//              (S15 §5) is RISC-V's boot convention — the reset vector runs a
//              small M-mode stub that leaves the hart id in a0 and a device tree
//              pointer in a1 before jumping to a payload entry. Booting straight
//              into the payload at the memory window base cannot express that:
//              there is nowhere for the a0/a1 setup to live and no entry for a
//              harness to point at. So reset PC moves here (eth_rv_pkg::RESET_PC)
//              and the payload becomes an ordinary image loaded at any entry.
//
//              CONTENT (see rtl/eth_rv/rom/boot_rom.S, the source of truth):
//
//                0x1000  auipc t0, 0          t0 = ROM base
//                0x1004  lui   a1, 0x80002    a1 = sign-extended 0x8000_2000
//                0x1008  slli  a1, a1, 32     ...
//                0x100a  srli  a1, a1, 32     a1 = 0x0000_0000_8000_2000 (DTB)
//                0x100c  csrr  a0, mhartid    a0 = hart id (single hart: 0)
//                0x1010  ld    t0, 32(t0)     t0 = the 64-bit payload entry
//                0x1014  jr    t0             hand off to the payload
//                0x1020  .dword <entry>       words 8/9: the payload entry
//
//              The entry word is DATA, not code, exactly as in Spike's own reset
//              vector (`sim_t::set_rom`, riscv/sim.cc: word 6 of the ROM holds
//              the start PC). A harness points the same ROM at any payload entry
//              by patching those two words in the loaded image (the testbench's
//              `+entry=<addr>`), so one ROM boots every corpus program.
//
//              THE STEP-COUNT WORD (offset 28, word 7) is the OTHER number in the
//              image the SoC consumes: the number of instructions the stub runs
//              before it hands off. `boot_rom.S` emits it as a link-time symbol
//              difference of the stub's own bytes (with `.option norvc`, so
//              instructions == bytes / 4), which is what makes it derived rather
//              than typed, and this module exports it as `stub_steps_o`. The CLINT
//              swallows exactly that many step pulses, so editing the stub either
//              fits the fixed pre-entry area (and the count follows) or fails the
//              build; the time/`mtime` cadence can no longer drift silently when
//              the stub changes length. Zero means the image is not ours (or
//              boot_rom.S lost the word) — the testbench rejects that before reset.
//
//              LOADING: the array is NOT initialised here — this module is pure
//              RTL with no file names baked in. The testbench preloads it before
//              reset from the checked-in hex image (`+rom=<file>`, generated by
//              rom/build_rom.py), exactly as it preloads the DRAM image, which
//              keeps the image path in the harness instead of in the RTL and
//              keeps `--lint-only` free of file I/O. Verification of what is in
//              the ROM is therefore binary: the image is checked in and
//              regenerable, and `entry_o` below lets the testbench confirm the
//              entry word it patched is the one the stub will jump to.
//
//              READ MODEL: one combinational port, addressed with the 8-byte
//              ALIGNED beat address (the caller aligns: `{addr[63:3], 3'b000}`)
//              and returning the eight bytes at that beat in lane order, which
//              is the shape the core's D port consumes. Read-only: a store is
//              NOT the ROM's to answer — `eth_rv_mmio_mux` turns it into the
//              architectural access fault, matching Spike's `rom_device_t`
//              (`store` returns false; `load` succeeds anywhere inside the
//              region).
// Maintainer:  BaiTian6641
// Created:     2026-09-12
// Tags:        RTL, SYNTH
// Plan-Ref:    ethereal-plan/components/C14-eth_rv-RV64核心.md §4 (MMIO via the D port),
//              §6 (boot path) ·
//              ethereal-plan/subsystems/S15-应用处理器子系统.md §5 (DDR-less boot:
//              BootROM + on-chip memory, a0/a1 handoff)
// Notes:       Pure combinational read; no clock, no reset, no state beyond the
//              preloaded array (one image, loaded once before reset). The array
//              is deliberately a module-level `logic [31:0]` vector so the
//              testbench can $readmemh into it hierarchically, the same way it
//              preloads the DRAM stub's memory. No vendor primitives.
module eth_rv_boot_rom #(
    parameter logic [63:0] BASE       = 64'h0000_0000_0000_1000,  // ROM_BASE (S3 contract)
    parameter int unsigned BYTES      = 4096,                     // 4 KiB region
    parameter int unsigned ENTRY_WORD = 8,                        // offset 32: the 64-bit entry
    parameter int unsigned STUB_WORD  = 7                         // offset 28: the stub's step count
) (
    // ---- read port (combinational; addr_i is the 8-byte aligned beat address) ----
    input  logic [63:0] addr_i,
    output logic        sel_o,     // addr_i is inside this ROM's region
    output logic [63:0] rdata_o,   // the eight bytes at addr_i (lane 0 = addr_i[2:0] == 0)
    output logic [63:0] entry_o,   // the payload entry word (what the stub will jump to)
    output logic [13:0] stub_steps_o  // the stub's instruction count (the CLINT's step skip)
);

    localparam int unsigned WORDS = BYTES / 4;            // 32-bit words in the region
    localparam int unsigned WIW   = $clog2(WORDS);        // word-index width
    localparam logic [63:0] LIMIT = BASE + 64'(BYTES);
    localparam int unsigned BIW   = WIW - 1;              // 8-byte beat index width
    localparam logic [WIW-1:0] ENTRY_LO = WIW'(ENTRY_WORD);      // low word of the entry
    localparam logic [WIW-1:0] ENTRY_HI = WIW'(ENTRY_WORD + 1);  // ... and its high word
    localparam logic [WIW-1:0] STUB_IDX = WIW'(STUB_WORD);       // the step-count word

    // Preloaded by the testbench before reset (see the header): one image.
    // verilator lint_off UNDRIVEN
    logic [31:0] rom [0:WORDS-1];
    // verilator lint_on UNDRIVEN

    logic [BIW-1:0] bi;     // 8-byte beat index inside the region
    logic [WIW-1:0] wi;     // low 32-bit word of that beat

    assign bi      = BIW'((addr_i - BASE) >> 3);
    assign sel_o   = (addr_i >= BASE) && (addr_i < LIMIT);
    assign wi      = {bi, 1'b0};
    assign rdata_o = sel_o ? {rom[wi + WIW'(1)], rom[wi]} : 64'd0;
    assign entry_o = {rom[ENTRY_HI], rom[ENTRY_LO]};
    // The stub's instruction count: a word of the image, so the CLINT's step skip
    // and the image the core actually executes cannot disagree (see the header).
    assign stub_steps_o = rom[STUB_IDX][13:0];

endmodule
`default_nettype wire
