# SPDX-License-Identifier: MIT
"""Ethereal runtime security package (E2-SEC1).

Public API: the ``capabilities.yaml`` parser/validator and the EMRI v0.6
capability-declaration encoding, re-exported from :mod:`security.capcheck`.
"""
from .capcheck import (
    CAP_DECL_BITS,
    CAP_STATUS_CHECKED,
    CAP_STATUS_DENIED,
    CAP_STATUS_DENIED_IO_MASK,
    CAP_STATUS_DENIED_IO_SHIFT,
    CAP_STATUS_THROTTLED,
    IO_DIRS,
    SIM_ALLOWED_IO_MASK,
    SIM_ALLOWED_SVC_MASK,
    SIM_SERVICE_INDEX,
    SVC_ACCESS,
    Capabilities,
    CapabilityDenied,
    CapabilityError,
    CapabilitySchemaError,
    CapStatus,
    IoDecl,
    IoDir,
    SvcAccess,
    SvcDecl,
    cap_status_decode,
    cap_status_encode,
    load_and_check,
    load_capabilities,
    to_emri_bitmaps,
    validate_grantable,
    validate_grantable_sim,
    validate_schema,
)

__all__ = [
    "CAP_DECL_BITS",
    "CAP_STATUS_CHECKED",
    "CAP_STATUS_DENIED",
    "CAP_STATUS_DENIED_IO_MASK",
    "CAP_STATUS_DENIED_IO_SHIFT",
    "CAP_STATUS_THROTTLED",
    "IO_DIRS",
    "SIM_ALLOWED_IO_MASK",
    "SIM_ALLOWED_SVC_MASK",
    "SIM_SERVICE_INDEX",
    "SVC_ACCESS",
    "CapStatus",
    "Capabilities",
    "CapabilityDenied",
    "CapabilityError",
    "CapabilitySchemaError",
    "IoDecl",
    "IoDir",
    "SvcAccess",
    "SvcDecl",
    "cap_status_decode",
    "cap_status_encode",
    "load_and_check",
    "load_capabilities",
    "to_emri_bitmaps",
    "validate_grantable",
    "validate_grantable_sim",
    "validate_schema",
]
