`default_nettype none
// SPDX-License-Identifier: CERN-OHL-S-2.0
// Module:      tb_bmc_script (testbench, self-checking)
// Description: E2-AST1 MCU scripted deployment — the BMC runs a
//              flash-resident deployment script through its own EFP/EMRI/OCC
//              machinery (no WASM runtime; phase-2 circuit-breaker degraded
//              demo). SIM-SCOPED command path per the emri-v0.md sec 3.6
//              precedent: EFP_CMD=SCRIPT (10) + EFP_REGION = script slot,
//              answered only by the firmware that installs the interpreter.
//
//                host BFM --AXI4--+
//                                 v
//                NEORV32 --XBUS--> eth_wb2axi --> eth_axi_xbar (2 masters)
//                                                    | 2 slaves
//                       +----------------------------+--------------------+
//                       v                                                 v
//             emri_axi_adapter -> emri_regfile          tb_scriptflash (model)
//             (EFP staging + status/err)                "external flash"
//                       | OCC master                    128 words: the
//                       v                                deployment scripts
//                 occ_top --fbus--> fabric_top (2x2 CLB)  (slot 0/1)
//                            +-> column_cfg_ram (readback target)
//
//              The firmware (bmc-fw/script/, real C) is the PRODUCTION daemon
//              (daemon.c: Ed25519 verify + OCC lifecycle) plus script/script.c
//              registered as the EFP_CMD_SCRIPT extension handler. The script
//              is GENERATED by script/gen_deploy_scripts.py (deterministic)
//              and read word-wise over XBUS at run time.
//
//              Scenario (script format v1; script/script.h):
//                0. boot: banner + EMRI MAGIC/CAP probe + EFP-SPI init +
//                   "daemon ready (script deploy)".
//                1. slot 0 (CRC-gated): start marker -> WAIT settle ->
//                   DEPLOY r0 = the daemon's OWN EFP_CMD_RUN path (Ed25519
//                   verify -> ALLOC -> BLANK -> LOAD (the host streams
//                   OCC_WDATA) -> READBACK -> RUNNING with EFP_ERR=0) ->
//                   POLL EFP_STATUS.state==RUNNING -> CHECK_ERR 0 -> "region
//                   0 RUNNING" marker -> WAIT (hold RUNNING so the TB can
//                   observe the real fabric) -> LOOP x2 markers (LOOPEND) ->
//                   STOP r0 -> POLL EFP_STATUS.state==STOPPED -> CHECK_ERR 0
//                   -> "region 0 stopped" marker -> END.
//                2. integrity negative: slot 1's header CRC corrupted in the
//                   flash model -> the interpreter refuses BEFORE any op
//                   ("script: err crc bad"), the command fails bad_cmd, and
//                   the fabric/region table are untouched.
//                3. image negative: slot 1 intact, host-staged SIGNATURE
//                   tampered -> the deploy reaches the Ed25519 gate, fails
//                   bad_sig (EFP_ERR=1 sticky, state ERROR), the script
//                   asserts it via CHECK_ERR and reports "bad_sig rejected";
//                   the fabric is untouched (no ALLOC/BLANK).
//
//              Register/observable contract: EFP_STATUS (RUNNING while the
//              script holds, STOPPED + busy=0 at the end), EFP_ERR (0 after
//              the scripted run, 1 sticky after the scripted reject),
//              MON_RECFG_COUNT.region0 == 1 (one completed deploy),
//              column_cfg_ram holds the image-A frame while RUNNING, and the
//              UART markers ("AST1: ...") prove the script's own ops.
//
//              SPEC ASK (NOT done here; spec changes are not this task's):
//              EFP_CMD=10 + R_SCRIPT_STATUS (proposed 0x3A) in emri-v0.md;
//              until then the slot index rides EFP_REGION and the script
//              verdict is UART-only (an interpreter error maps to EFP_ERR=6).
//              ASSUMPTION (TBD, 2026-09-12): the flash stand-in is a TB-local
//              non-volatile AXI model at 0x4001_0000 (same convention as the
//              E1-BMC2 fwupdate TB); real SPI flash + Boot-ROM anchoring stay
//              E2-SEC1/E2-BMC scope.
// Maintainer:  BaiTian6641
// Created:     2026-09-12
// Tags:        TESTBENCH
// Plan-Ref:    ethereal-spec/control/emri-v0.md sec 3.2/§3.4/§3.6;
//              ethereal-plan/subsystems/S05-BMC与EMRI-mFSM.md §2.2/§2.3;
//              ethereal-plan/phases/phase-2-异构与双平台.md §3 (circuit-breaker:
//              MCU scripted deployment while the WASM line is blocked).
// Notes:       Verilator --binary --timing (Makefile test-sv; same reason as
//              the other real-C-firmware BMC TBs). Two Ed25519 verifies
//              (~0.84 s sim each) dominate the run. UART bit time = 2 clk.
//              The WASM acceptance (wasmtime/WAMR Type-F container execution)
//              is NOT covered by this TB — it stays blocked on this machine.
`timescale 1ns/1ps

module tb_bmc_script;
  import emri_pkg::*;

  // -- Fabric geometry (2x2 homogeneous CLB; mirrors tb_bmc_daemon) --------
  localparam int R = 2, C = 2, W = 12, N = 8, K = 4, EXT_IN = 18;
  localparam int OBS_W = R * C * N;                 // 32

  // -- Script container/geometry (bmc-fw/script/script.h) -----------------
  localparam int    SLOT_WORDS   = 64;              // per script slot
  localparam int    SCRIPT_SLOTS = 2;
  localparam logic [31:0] SCRIPT_MAGIC = 32'h53435231;  // "SCR1"
  localparam logic [7:0]  EFP_CMD_SCRIPT_W = 8'd10;     // sim-scoped (daemon.h)
  localparam int    REGION0      = 0;
  localparam logic [3:0] EFP_S_RUNNING_W = 4'd6;
  localparam logic [3:0] EFP_S_STOPPED_W = 4'd8;
  localparam logic [3:0] EFP_S_ERROR_W   = 4'd7;
  localparam logic [15:0] R_EFP_STATUS_W = 16'h16;
  localparam logic [15:0] R_EFP_ERR_W    = 16'h17;
  localparam logic [15:0] R_EFP_CMD_W    = 16'h13;
  localparam logic [15:0] R_EFP_REGION_W = 16'h14;
  localparam int    IMG_A_WORDS  = 12;              // DAEMON_IMG_A_NWORDS

  // -- Timing -------------------------------------------------------------
  localparam int CLK_PERIOD_NS = 10;                // 100 MHz
  localparam int BIT_NS = 2 * CLK_PERIOD_NS;        // 20 ns/bit

  logic clk;
  logic rst_n;

  // -- DUT: bmc_core (NEORV32 + eth_wb2axi inside) = AXI master 0 ---------
  logic        uart0_txd;
  logic        uart0_rxd;

  logic        awvalid, awready;
  logic [31:0] awaddr;
  logic [2:0]  awprot;
  logic        wvalid, wready;
  logic [31:0] wdata;
  logic [3:0]  wstrb;
  logic        bvalid, bready;
  logic [1:0]  bresp;
  logic        arvalid, arready;
  logic [31:0] araddr;
  logic [2:0]  arprot;
  logic        rvalid, rready;
  logic [31:0] rdata;
  logic [1:0]  rresp;

  bmc_core dut (
      .clk_i         (clk),
      .rst_ni        (rst_n),
      .uart0_txd_o   (uart0_txd),
      .uart0_rxd_i   (uart0_rxd),
      .m_axi_awvalid (awvalid),
      .m_axi_awready (awready),
      .m_axi_awaddr  (awaddr),
      .m_axi_awprot  (awprot),
      .m_axi_wvalid  (wvalid),
      .m_axi_wready  (wready),
      .m_axi_wdata   (wdata),
      .m_axi_wstrb   (wstrb),
      .m_axi_bvalid  (bvalid),
      .m_axi_bready  (bready),
      .m_axi_bresp   (bresp),
      .m_axi_arvalid (arvalid),
      .m_axi_arready (arready),
      .m_axi_araddr  (araddr),
      .m_axi_arprot  (arprot),
      .m_axi_rvalid  (rvalid),
      .m_axi_rready  (rready),
      .m_axi_rdata   (rdata),
      .m_axi_rresp   (rresp),
      .dbg_en_i      (1'b0),
      // SDI tied off (CS high = idle): this TB drives no EFP-SPI traffic.
      .sdi_clk_i     (1'b0),
      .sdi_csn_i     (1'b1),
      .sdi_dat_i     (1'b1),
      .sdi_dat_o     (),
      .heartbeat_o   ()
  );

  // -- Host BFM = AXI master 1 --------------------------------------------
  logic        h_awvalid, h_awready;
  logic [31:0] h_awaddr;
  logic        h_wvalid, h_wready;
  logic [31:0] h_wdata;
  logic        h_bvalid, h_bready;
  logic [1:0]  h_bresp;
  logic        h_arvalid, h_arready;
  logic [31:0] h_araddr;
  logic        h_rvalid, h_rready;
  logic [31:0] h_rdata;
  logic [1:0]  h_rresp;

  // -- eth_axi_xbar: 2 masters x 2 slaves (+ decode-error slave) ----------
  // slave 0: EMRI window 512 B @ 0x4000_2000 (mask 0xFFFF_FE00)
  // slave 1: script-flash window 512 B @ 0x4001_0000 (mask 0xFFFF_FE00)
  localparam int N_MST = 2, N_SLV = 2, AXI_AW = 32, AXI_DW = 32, AXI_IDW = 1;
  localparam int XIDW = AXI_IDW + 1;
  localparam logic [2*N_SLV*AXI_AW-1:0] ADDR_MAP =
      {32'hFFFF_FE00, 32'hFFFF_FE00, 32'h4001_0000, 32'h4000_2000};

  logic [N_SLV-1:0]        m_awvalid, m_awready;
  logic [N_SLV*AXI_AW-1:0] m_awaddr;
  logic [N_SLV*XIDW-1:0]   m_awid;
  logic [N_SLV-1:0]        m_wvalid, m_wready;
  logic [N_SLV*AXI_DW-1:0] m_wdata;
  logic [N_SLV*4-1:0]      m_wstrb;
  logic [N_SLV-1:0]        m_bvalid, m_bready;
  logic [N_SLV*2-1:0]      m_bresp;
  logic [N_SLV-1:0]        m_arvalid, m_arready;
  logic [N_SLV*AXI_AW-1:0] m_araddr;
  logic [N_SLV*XIDW-1:0]   m_arid;
  logic [N_SLV-1:0]        m_rvalid, m_rready;
  logic [N_SLV*AXI_DW-1:0] m_rdata;
  logic [N_SLV*2-1:0]      m_rresp;

  eth_axi_xbar #(
      .N_MST(N_MST), .N_SLV(N_SLV), .AXI_AW(AXI_AW), .AXI_DW(AXI_DW),
      .AXI_IDW(AXI_IDW), .AXI_XIDW(XIDW), .ADDR_MAP(ADDR_MAP)
  ) u_xbar (
      .clk_i(clk), .rst_ni(rst_n),
      .s_awvalid({h_awvalid, awvalid}), .s_awready({h_awready, awready}),
      .s_awaddr({h_awaddr, awaddr}),    .s_awid(2'b00),
      .s_wvalid({h_wvalid, wvalid}),    .s_wready({h_wready, wready}),
      .s_wdata({h_wdata, wdata}),       .s_wstrb({4'hF, wstrb}),
      .s_bvalid({h_bvalid, bvalid}),    .s_bready({h_bready, bready}),
      .s_bid(),                         .s_bresp({h_bresp, bresp}),
      .s_arvalid({h_arvalid, arvalid}), .s_arready({h_arready, arready}),
      .s_araddr({h_araddr, araddr}),    .s_arid(2'b00),
      .s_rvalid({h_rvalid, rvalid}),    .s_rready({h_rready, rready}),
      .s_rid(),                         .s_rdata({h_rdata, rdata}),
      .s_rresp({h_rresp, rresp}),
      .m_awvalid(m_awvalid), .m_awready(m_awready), .m_awaddr(m_awaddr), .m_awid(m_awid),
      .m_wvalid(m_wvalid),   .m_wready(m_wready),   .m_wdata(m_wdata),   .m_wstrb(m_wstrb),
      .m_bvalid(m_bvalid),   .m_bready(m_bready),   .m_bid({2*XIDW{1'b0}}), .m_bresp(m_bresp),
      .m_arvalid(m_arvalid), .m_arready(m_arready), .m_araddr(m_araddr), .m_arid(m_arid),
      .m_rvalid(m_rvalid),   .m_rready(m_rready),   .m_rid({2*XIDW{1'b0}}), .m_rdata(m_rdata),
      .m_rresp(m_rresp)
  );

  // -- slave 0: emri_axi_adapter + emri_regfile (BMC mode) ----------------
  logic        host_req, host_we, host_ready;
  logic [1:0]  host_op;
  logic [15:0] host_addr;
  logic [31:0] host_wdata, host_rdata;

  emri_axi_adapter #(
      .AXI_AW(AXI_AW), .AXI_DW(AXI_DW), .REG_BASE(32'h4000_2000), .WIN_WORDS(96)
  ) u_emri_adapter (
      .clk_i(clk), .rst_ni(rst_n),
      .s_axi_awvalid(m_awvalid[0]), .s_axi_awready(m_awready[0]),
      .s_axi_awaddr(m_awaddr[0*AXI_AW +: AXI_AW]), .s_axi_awprot(3'b000),
      .s_axi_wvalid(m_wvalid[0]),   .s_axi_wready(m_wready[0]),
      .s_axi_wdata(m_wdata[0*AXI_DW +: AXI_DW]),  .s_axi_wstrb(m_wstrb[0*4 +: 4]),
      .s_axi_bvalid(m_bvalid[0]),   .s_axi_bready(m_bready[0]),
      .s_axi_bresp(m_bresp[0*2 +: 2]),
      .s_axi_arvalid(m_arvalid[0]), .s_axi_arready(m_arready[0]),
      .s_axi_araddr(m_araddr[0*AXI_AW +: AXI_AW]), .s_axi_arprot(3'b000),
      .s_axi_rvalid(m_rvalid[0]),   .s_axi_rready(m_rready[0]),
      .s_axi_rdata(m_rdata[0*AXI_DW +: AXI_DW]),  .s_axi_rresp(m_rresp[0*2 +: 2]),
      .host_req_o(host_req),     .host_we_o(host_we),   .host_op_o(host_op),
      .host_addr_o(host_addr),   .host_wdata_o(host_wdata),
      .host_rdata_i(host_rdata), .host_ready_i(host_ready)
  );

  // -- EMRI -> OCC -> fabric (v0 cfg-addr-addressed frame format) ---------
  logic [1:0]  occ_cmd;
  logic        occ_cmd_valid, occ_cmd_ready;
  logic [15:0] occ_frame_addr, occ_word_count;
  logic [31:0] occ_wdata;
  logic        occ_wdata_valid, occ_wdata_ready;
  logic [2:0]  occ_status;
  logic        occ_crc_error;
  logic [7:0]  occ_region_locks;
  logic        occ_global_lock;

  logic [15:0] fbus_addr;
  logic [31:0] fbus_wdata;
  logic        fbus_we, fbus_re;
  logic [31:0] fbus_rdata;

  logic [OBS_W-1:0]  clb_out_obs;
  logic [R*C*32-1:0] mem_vd_obs;
  logic [R*C*48-1:0] dsp_vp_obs;

  logic [31:0] occ_expect_crc_w;   // v0.5 §3.1.1 (OCC expected-CRC gate)
  logic [31:0] occ_crc_result_w;   // v0.5 §3.1.1 (OCC running CRC)

  emri_regfile #(
      .HAS_BMC(1'b1), .NUM_REGIONS(2), .PLATFORM_ID(32'h0),
      .REGION0_INFO(32'h0202_0002), .REGION1_INFO(32'h0202_0002)
  ) u_emri (
      .clk_i(clk), .rst_ni(rst_n),
      .host_req_i(host_req), .host_we_i(host_we), .host_op_i(host_op),
      .host_addr_i(host_addr), .host_wdata_i(host_wdata),
      .host_rdata_o(host_rdata), .host_ready_o(host_ready),
      .occ_cmd_o(occ_cmd), .occ_cmd_valid_o(occ_cmd_valid),
      .occ_cmd_ready_i(occ_cmd_ready),
      .occ_frame_addr_o(occ_frame_addr), .occ_word_count_o(occ_word_count),
      .occ_wdata_o(occ_wdata), .occ_wdata_valid_o(occ_wdata_valid),
      .occ_wdata_ready_i(occ_wdata_ready),
      .occ_status_i(occ_status), .occ_crc_error_i(occ_crc_error),
      .occ_region_locks_o(occ_region_locks), .occ_global_lock_o(occ_global_lock),
      .dec_start_o(), .dec_col_o(), .dec_busy_i(1'b0),
      .occ_expect_crc_o(occ_expect_crc_w),
      .occ_crc_result_i(occ_crc_result_w),
      // v0.7 §3.9 context engine: not exercised by this demo (tied off).
      .ctx_start_o(), .ctx_mode_o(), .ctx_words_o(),
      .ctx_busy_i(1'b0), .ctx_done_i(1'b0), .ctx_err_i(1'b0)
  );

  occ_top #(.ADDR_W(16), .DATA_W(32)) u_occ (
      .clk_i(clk), .rst_ni(rst_n),
      .cmd_i(occ_cmd), .cmd_valid_i(occ_cmd_valid), .cmd_ready_o(occ_cmd_ready),
      .frame_addr_i(occ_frame_addr), .word_count_i(occ_word_count),
      .wdata_i(occ_wdata), .wdata_valid_i(occ_wdata_valid),
      .wdata_ready_o(occ_wdata_ready),
      .fbus_addr_o(fbus_addr), .fbus_wdata_o(fbus_wdata),
      .fbus_we_o(fbus_we), .fbus_re_o(fbus_re), .fbus_rdata_i(fbus_rdata),
      .status_o(occ_status), .crc_error_o(occ_crc_error),
      .region_locks_i(occ_region_locks), .global_lock_i(occ_global_lock),
      .expect_crc_i(occ_expect_crc_w),
      .crc_result_o(occ_crc_result_w)
  );

  // Readback target for the OCC READBACK verify (fabric_top itself has no cfg
  // read port — C03 §0 sim model, same role as in tb_bmc_daemon).
  column_cfg_ram #(.ADDR_W(16), .DATA_W(32), .DEPTH(8192)) u_cfgram (
      .clk(clk), .we(fbus_we), .re(fbus_re),
      .addr(fbus_addr), .wdata(fbus_wdata), .rdata(fbus_rdata)
  );

  fabric_top #(
      .R(R), .C(C), .W(W), .N(N), .K(K), .EXT_IN(EXT_IN)
  ) u_fabric (
      .clk_i(clk), .rst_ni(rst_n),
      .cfg_we_i(fbus_we), .cfg_addr_i(fbus_addr), .cfg_data_i(fbus_wdata),
      .clb_out_obs_o(clb_out_obs),
      .mem_vd_obs_o(mem_vd_obs),
      .dsp_vp_obs_o(dsp_vp_obs),
      .scan_en_i(1'b0),
      .scan_in_i(1'b0),
      .scan_out_o()
  );

  // -- slave 1: tb_scriptflash — non-volatile "external flash" stand-in ----
  tb_scriptflash #(.BASE(32'h4001_0000), .WORDS(128)) u_scriptflash (
      .clk_i(clk), .rst_ni(rst_n),
      .s_axi_awvalid(m_awvalid[1]), .s_axi_awready(m_awready[1]),
      .s_axi_awaddr(m_awaddr[1*AXI_AW +: AXI_AW]),
      .s_axi_wvalid(m_wvalid[1]),   .s_axi_wready(m_wready[1]),
      .s_axi_wdata(m_wdata[1*AXI_DW +: AXI_DW]), .s_axi_wstrb(m_wstrb[1*4 +: 4]),
      .s_axi_bvalid(m_bvalid[1]),   .s_axi_bready(m_bready[1]),
      .s_axi_bresp(m_bresp[1*2 +: 2]),
      .s_axi_arvalid(m_arvalid[1]), .s_axi_arready(m_arready[1]),
      .s_axi_araddr(m_araddr[1*AXI_AW +: AXI_AW]),
      .s_axi_rvalid(m_rvalid[1]),   .s_axi_rready(m_rready[1]),
      .s_axi_rdata(m_rdata[1*AXI_DW +: AXI_DW]), .s_axi_rresp(m_rresp[1*2 +: 2])
  );

  // -- Clock ---------------------------------------------------------------
  initial clk = 1'b0;
  always #(CLK_PERIOD_NS / 2) clk = ~clk;

  // -- Firmware preload (DMEM-exec bootstrap; same backdoor as tb_bmc_fw) --
  initial begin
      // #1: defer past the netlist's own time-0 IMEM ROM fill (it would
      // otherwise clobber the preload; the core is still in reset).
      #1;
      $readmemh("generated/bmc/script_boot.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_imem_enabled_neorv32_imem_inst
                .imem_rom_imem_rom_inst.n7280);
      $readmemh("generated/bmc/script_dmem_lane0.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[0]_ram_inst .spram);
      $readmemh("generated/bmc/script_dmem_lane1.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[1]_ram_inst .spram);
      $readmemh("generated/bmc/script_dmem_lane2.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[2]_ram_inst .spram);
      $readmemh("generated/bmc/script_dmem_lane3.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[3]_ram_inst .spram);
      // The deployment-script window (gen_deploy_scripts.py output): slot 0 =
      // deploy, slot 1 = reject. Non-volatile: no reset clear.
      $readmemh("generated/bmc/script_window.hex", u_scriptflash.mem);
  end

  // -- Signed-image vectors (gen_daemon_vectors.py; same corpus as
  //    tb_bmc_daemon: image A (TFF) + digest/sig + a tampered sig) ----------
  `include "tb_daemon_vectors.svh"

  // ============================================================================
  // Concurrent UART 8N1 receiver (idle-high, start bit low, LSB first)
  // ============================================================================
  localparam int MAXB = 8192;
  bit [7:0] rxq [0:MAXB-1];
  integer   rxn = 0;

  always @(negedge uart0_txd) begin : uart_rx
      integer i;
      logic [7:0] b;
      #(BIT_NS / 2);
      if (uart0_txd === 1'b0) begin
          b = 8'h00;
          for (i = 0; i < 8; i = i + 1) begin
              #(BIT_NS);
              b[i] = uart0_txd;
          end
          #(BIT_NS);
          if (uart0_txd === 1'b1 && rxn < MAXB) begin
              rxq[rxn] = b;
              rxn = rxn + 1;
          end
      end
  end

  // ============================================================================
  // Check helpers
  // ============================================================================
  integer errors = 0;

  // ============================================================================
  // Live UART trace (diagnostics): echo each newly received byte as the
  // firmware prints it, so a long/failing phase is visible immediately
  // (the firmware's own log is the ground truth for where it stopped).
  // ============================================================================
  localparam bit RX_TRACE = 1'b1;

  initial begin : rx_trace
      integer last, i;
      last = 0;
      forever begin
          #(100000);   // 100 us sim poll
          if (RX_TRACE && rxn != last) begin
              $write("[rx @%0dns +%0d] ", $time, rxn - last);
              for (i = last; i < rxn; i = i + 1) begin
                  if (rxq[i] == 8'h0a) $write("\n");
                  else if (rxq[i] < 8'h20 || rxq[i] > 8'h7e)
                      $write("<%02x>", rxq[i]);
                  else $write("%c", rxq[i]);
              end
              last = rxn;
          end
          if (!RX_TRACE) last = rxn;
      end
  end

  task automatic chk(input logic cond, input string msg);
      begin
          if (cond) $display("  ok: %0s", msg);
          else begin
              errors = errors + 1;
              $display("  FAIL: %0s", msg);
          end
      end
  endtask

  // Dump everything the firmware has printed so far (diagnostics for a failed
  // wait: the firmware's own trace is the ground truth for what went wrong).
  task automatic dump_uart;
      integer i;
      begin
          $write("  uart rx (%0d bytes): ", rxn);
          for (i = 0; i < rxn; i = i + 1) begin
              if (rxq[i] == 8'h0a) $write("\n");
              else if (rxq[i] < 8'h20 || rxq[i] > 8'h7e) $write("<%02x>", rxq[i]);
              else $write("%c", rxq[i]);
          end
          $write("\n");
      end
  endtask

  // Block until the received stream CONTAINS s (containment, like
  // tb_bmc_fwupdate) — the daemon's own logs interleave with the script's.
  task automatic wait_uart_contains(input string s, input string tag);
      integer to, base, j;
      logic found, m;
      begin
          to = 0;
          found = 1'b0;
          while (!found && to < 2000000) begin
              for (base = 0; base + s.len() <= rxn; base = base + 1) begin
                  m = 1'b1;
                  for (j = 0; j < s.len(); j = j + 1)
                      if (rxq[base + j] !== s[j]) m = 1'b0;
                  if (m) begin
                      found = 1'b1;
                      break;
                  end
              end
              if (!found) begin
                  #(1000);
                  to = to + 1;
              end
          end
          chk(found, tag);
          if (!found) dump_uart();
      end
  endtask

  // Count non-overlapping occurrences of s in the received stream (the LOOP
  // op's evidence: the body ran exactly N times).
  function automatic integer count_uart(input string s);
      integer base, j, n;
      logic m;
      begin
          n = 0;
          base = 0;
          while (base + s.len() <= rxn) begin
              m = 1'b1;
              for (j = 0; j < s.len(); j = j + 1)
                  if (rxq[base + j] !== s[j]) m = 1'b0;
              if (m) begin
                  n = n + 1;
                  base = base + s.len();
              end else begin
                  base = base + 1;
              end
          end
          count_uart = n;
      end
  endfunction

  // ============================================================================
  // Host BFM (AXI master 1) — drive on negedge, sample handshakes on posedge
  // ============================================================================
  localparam logic [31:0] EMRI_BASE = 32'h4000_2000;

  task automatic axi_wr(input logic [31:0] a, input logic [31:0] d);
      logic aw_done, w_done;
      begin
          @(negedge clk);
          h_awaddr = a; h_awvalid = 1'b1;
          h_wdata  = d; h_wvalid  = 1'b1;
          h_bready = 1'b1;
          aw_done = 1'b0; w_done = 1'b0;
          while (!(aw_done && w_done)) begin
              @(posedge clk);
              if (h_awvalid && h_awready) aw_done = 1'b1;
              if (h_wvalid  && h_wready)  w_done  = 1'b1;
          end
          @(negedge clk);
          h_awvalid = 1'b0; h_wvalid = 1'b0;
          while (!h_bvalid) @(posedge clk);
          @(negedge clk);
          h_bready = 1'b0;
      end
  endtask

  task automatic axi_rd(input logic [31:0] a, output logic [31:0] d);
      logic ar_done, r_done;
      begin
          @(negedge clk);
          h_araddr = a; h_arvalid = 1'b1; h_rready = 1'b1;
          ar_done = 1'b0;
          while (!ar_done) begin
              @(posedge clk);
              if (h_arvalid && h_arready) ar_done = 1'b1;
          end
          @(negedge clk);
          h_arvalid = 1'b0;
          d = 32'h0; r_done = 1'b0;
          while (!r_done) begin
              @(posedge clk);
              if (h_rvalid) begin
                  d      = h_rdata;
                  r_done = 1'b1;
              end
          end
          @(negedge clk);
          h_rready = 1'b0;
      end
  endtask

  task automatic host_wr(input logic [15:0] word, input logic [31:0] d);
      begin
          axi_wr(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  task automatic host_rd(input logic [15:0] word, output logic [31:0] d);
      begin
          axi_rd(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  // Poll EFP_STATUS until busy=0 (spec §3.2: the host MUST see busy=0 before
  // the next EFP_CMD write).
  task automatic host_wait_idle(input string tag);
      logic [31:0] s;
      integer to;
      begin
          to = 0;
          host_rd(R_EFP_STATUS_W, s);
          while (s[4] && to < 100000) begin
              host_rd(R_EFP_STATUS_W, s);
              to = to + 1;
          end
          chk(!s[4], tag);
      end
  endtask

  // ---- image staging (spec §3.2 step 1) ---------------------------------
  localparam int SEL_A        = 0;   // image A, valid signature
  localparam int SEL_A_TAMPER = 1;   // image A, tampered signature

  task automatic host_stage(input integer sel, input logic [31:0] words,
                            input logic [31:0] region);
      integer k;
      begin
          for (k = 0; k < 8; k = k + 1)
              host_wr(R_IMG_DIGEST + 16'(k), DAEMON_IMG_A_DIGEST[k]);
          for (k = 0; k < 16; k = k + 1)
              host_wr(R_IMG_SIG + 16'(k),
                      (sel == SEL_A_TAMPER) ? DAEMON_IMG_A_SIG_TAMPER[k]
                                            : DAEMON_IMG_A_SIG[k]);
          host_wr(R_EFP_IMG_WORDS, words);
          host_wr(R_EFP_REGION, region);
      end
  endtask

  // Stream the frame words through OCC_WDATA (spec §3.2 step 5: the host
  // streams while the daemon supervises OCC_STATUS in LOAD).
  task automatic host_stream;
      integer k;
      begin
          for (k = 0; k < DAEMON_IMG_A_NWORDS; k = k + 1)
              host_wr(R_OCC_WDATA, DAEMON_IMG_A_WORDS[k]);
      end
  endtask

  task automatic ring_script(input logic [31:0] slot);
      begin
          host_wr(R_EFP_REGION_W, slot);                 // script slot index
          host_wr(R_EFP_CMD_W, {24'h0, EFP_CMD_SCRIPT_W});
      end
  endtask

  // ---- fabric observation (the REAL fabric outputs) ---------------------
  task automatic observe_toggle(input string tag);
      integer k;
      logic s0, s1;
      begin
          s0 = 1'b0; s1 = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[0] === 1'b0) s0 = 1'b1;
              if (clb_out_obs[0] === 1'b1) s1 = 1'b1;
          end
          chk(s0 && s1, tag);
      end
  endtask

  // ============================================================================
  // Test sequence (script format v1; bmc-fw/script/script.h)
  // ============================================================================
  logic [31:0] rd;
  logic [31:0] frame_shadow [0:IMG_A_WORDS-1];
  integer      k;
  logic        frame_ok;

  initial begin : main_seq
      // idle the host BFM + UART RX
      h_awvalid = 1'b0; h_awaddr = 32'h0;
      h_wvalid  = 1'b0; h_wdata  = 32'h0;
      h_bready  = 1'b0;
      h_arvalid = 1'b0; h_araddr = 32'h0;
      h_rready  = 1'b0;
      uart0_rxd = 1'b1;

      rst_n = 1'b0;
      repeat (20) @(posedge clk);
      rst_n = 1'b1;

      // ---- 0. boot ---------------------------------------------------------
      $display("[0] boot: script-deployment firmware on the real BMC chain");
      wait_uart_contains("bmc-fw script deploy demo boot\n", "boot banner");
      wait_uart_contains("EMRI MAGIC=45544852 CAP=00000001\n", "EMRI MAGIC/CAP probe");
      wait_uart_contains("efp-spi none (sim variant)\n",
                         "no EFP-SPI front-end in this variant (AXI host path)");
      wait_uart_contains("daemon ready (script deploy)\n",
                         "daemon poll loop + EFP_CMD_SCRIPT handler registered");

      // ---- 1. script slot 0: signed image deployed to region 0 ------------
      $display("[1] script slot 0 — deploy the signed image into region 0");
      host_stage(SEL_A, 32'(DAEMON_IMG_A_NWORDS), 32'd0);
      ring_script(32'd0);
      wait_uart_contains("script: run slot 0\n",
                         "slot header accepted (magic/version/length/CRC)");
      wait_uart_contains("script: deploy r0\n", "script DEPLOY r0 op issued");
      wait_uart_contains("verify ok\n", "Ed25519 signature verified (signed image)");
      wait_uart_contains("st LOAD\n", "deploy reached LOAD — host streams now");
      host_stream();
      wait_uart_contains("load ok\n", "OCC WRITE stream complete");
      wait_uart_contains("readback ok\n", "OCC READBACK CRC ok");
      wait_uart_contains("st RUNNING r0 done\n", "region 0 RUNNING");
      wait_uart_contains("script: poll 0016 ok\n", "script POLL saw EFP_STATUS");
      wait_uart_contains("script: err ok\n", "script CHECK_ERR = 0");
      wait_uart_contains("AST1: region 0 RUNNING\n", "script UART marker (RUNNING)");

      // The script holds RUNNING (WAIT op) — observe the real fabric + frame.
      observe_toggle("region 0 runs the signed image (clb_out_obs[0] toggles)");
      frame_ok = 1'b1;
      for (k = 0; k < IMG_A_WORDS; k = k + 1)
          if (u_cfgram.mem[k] !== DAEMON_IMG_A_WORDS[k]) frame_ok = 1'b0;
      chk(frame_ok, "column_cfg_ram holds the image-A frame while RUNNING");

      wait_uart_contains("AST1: tick\n", "LOOP body marker emitted");
      wait_uart_contains("AST1: region 0 stopped\n", "script UART marker (STOPPED)");
      wait_uart_contains("script: done ok\n", "script END reached, all checks ok");
      host_wait_idle("EFP_STATUS.busy cleared after the scripted command");
      host_rd(R_EFP_STATUS_W, rd);
      chk(rd[3:0] == EFP_S_STOPPED_W, "EFP_STATUS.state = STOPPED after script stop");
      host_rd(R_EFP_ERR_W, rd);
      chk(rd[7:0] == EFP_ERR_NONE, "EFP_ERR = 0 after the scripted run");
      chk(count_uart("AST1: tick\n") == 2, "LOOP op executed its body exactly twice");
      host_rd(R_MON_RECFG_COUNT, rd);
      chk(rd[15:0] == 32'd1, "MON_RECFG_COUNT.region0 == 1 (one completed deploy)");

      // ---- 2. integrity negative: corrupted script slot 1 CRC -------------
      $display("[2] script slot 1 with a corrupted header CRC — refused");
      for (k = 0; k < IMG_A_WORDS; k = k + 1) frame_shadow[k] = u_cfgram.mem[k];
      u_scriptflash.mem[SLOT_WORDS + 3] = u_scriptflash.mem[SLOT_WORDS + 3] ^ 32'h1;
      ring_script(32'd1);
      wait_uart_contains("script: err crc bad\n",
                         "interpreter CRC gate refused the slot (no op ran)");
      wait_uart_contains("err bad_cmd\n", "EFP_CMD_SCRIPT command failed with bad_cmd");
      host_wait_idle("busy cleared after the refused script");
      host_rd(R_EFP_ERR_W, rd);
      chk(rd[7:0] == EFP_ERR_BAD_CMD, "EFP_ERR = bad_cmd (6) for the refused script");
      host_rd(R_EFP_STATUS_W, rd);
      chk(rd[3:0] == EFP_S_ERROR_W, "EFP_STATUS.state = ERROR after the refusal");
      host_rd(R_MON_RECFG_COUNT, rd);
      chk(rd[15:0] == 32'd1, "no deploy happened (MON_RECFG_COUNT.region0 still 1)");
      // restore slot 1's header CRC
      u_scriptflash.mem[SLOT_WORDS + 3] = u_scriptflash.mem[SLOT_WORDS + 3] ^ 32'h1;
      chk(u_scriptflash.mem[SLOT_WORDS + 0] == SCRIPT_MAGIC, "slot 1 still intact");

      // ---- 3. image negative: tampered signature, script asserts bad_sig --
      $display("[3] script slot 1 with a TAMPERED staged signature — bad_sig");
      host_stage(SEL_A_TAMPER, 32'(DAEMON_IMG_A_NWORDS), 32'd0);
      ring_script(32'd1);
      wait_uart_contains("script: run slot 1\n", "slot 1 accepted after CRC restore");
      wait_uart_contains("script: deploy r0\n", "script DEPLOY r0 op issued");
      wait_uart_contains("err bad_sig\n", "Ed25519 gate refused the tampered image");
      wait_uart_contains("script: err ok\n", "script CHECK_ERR matched bad_sig (1)");
      wait_uart_contains("AST1: bad_sig rejected\n", "script UART marker (reject)");
      wait_uart_contains("script: done ok\n", "reject script END reached, check ok");
      host_wait_idle("busy cleared after the reject script");
      host_rd(R_EFP_ERR_W, rd);
      chk(rd[7:0] == EFP_ERR_BAD_SIG, "EFP_ERR = bad_sig (1) sticky after the script");
      host_rd(R_EFP_STATUS_W, rd);
      chk(rd[3:0] == EFP_S_ERROR_W, "EFP_STATUS.state = ERROR (deploy refused)");
      host_rd(R_MON_RECFG_COUNT, rd);
      chk(rd[15:0] == 32'd1, "rejected deploy never reached RUNNING (count still 1)");
      frame_ok = 1'b1;
      for (k = 0; k < IMG_A_WORDS; k = k + 1)
          if (u_cfgram.mem[k] !== frame_shadow[k]) frame_ok = 1'b0;
      chk(frame_ok, "rejected deploy left the fabric config untouched");

      // ---- report ----------------------------------------------------------
      if (errors == 0)
          $display("TEST PASSED: E2-AST1 MCU scripted deployment — flash script (CRC-gated) -> EFP_CMD_SCRIPT -> signed image deployed to region 0 (RUNNING, EFP_ERR=0) -> UART markers (LOOP) -> STOPPED; corrupted script + tampered signature refused");
      else
          $display("TEST FAILED: %0d errors", errors);
      $finish;
  end

  // -- Watchdog -------------------------------------------------------------
  initial begin
      // 2 Ed25519 verifies (~0.84 s sim each) + OCC deploys: ~5 s sim.
      repeat (20) #(1000000000);   // 20 s hard cap
      $display("TEST FAILED: watchdog timeout (rxn=%0d errors=%0d)", rxn, errors);
      $finish;
  end

endmodule

// ============================================================================
// tb_scriptflash — TB-local "external flash" stand-in (SIM MODEL, not RTL):
// an AXI4-Lite slave serving a word array. The storage has NO reset clear
// (non-volatile: the deployment scripts must survive the TB reset pulse); the
// TB preloads/corrupts it hierarchically (u_scriptflash.mem[...]) while the
// CPU is quiescent. Same shape as tb_fwflash (tb_bmc_fwupdate.sv).
// ============================================================================
module tb_scriptflash #(
    parameter logic [31:0] BASE = 32'h4001_0000,
    parameter int          WORDS = 128
) (
    input  logic        clk_i,
    input  logic        rst_ni,
    input  logic        s_axi_awvalid,
    output logic        s_axi_awready,
    input  logic [31:0] s_axi_awaddr,
    input  logic        s_axi_wvalid,
    output logic        s_axi_wready,
    input  logic [31:0] s_axi_wdata,
    input  logic [3:0]  s_axi_wstrb,
    output logic        s_axi_bvalid,
    input  logic        s_axi_bready,
    output logic [1:0]  s_axi_bresp,
    input  logic        s_axi_arvalid,
    output logic        s_axi_arready,
    input  logic [31:0] s_axi_araddr,
    output logic        s_axi_rvalid,
    input  logic        s_axi_rready,
    output logic [31:0] s_axi_rdata,
    output logic [1:0]  s_axi_rresp
);
    // Non-volatile storage (deliberately NO reset clear).
    logic [31:0] mem [0:WORDS-1];

    typedef enum logic [1:0] { S_IDLE = 2'd0, S_WRB = 2'd1, S_RD = 2'd2 } st_e;
    st_e st;
    logic [31:0] raddr_q;

    assign s_axi_awready = (st == S_IDLE) && s_axi_awvalid && s_axi_wvalid;
    assign s_axi_wready  = s_axi_awready;
    assign s_axi_arready = (st == S_IDLE) && s_axi_arvalid &&
                           !(s_axi_awvalid && s_axi_wvalid);

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            st           <= S_IDLE;
            raddr_q      <= 32'h0;
            s_axi_bvalid <= 1'b0;
            s_axi_rvalid <= 1'b0;
            s_axi_bresp  <= 2'b00;
            s_axi_rresp  <= 2'b00;
            s_axi_rdata  <= 32'h0;
        end else begin
            s_axi_bvalid <= 1'b0;   // default: pulse unless held below
            s_axi_rvalid <= 1'b0;
            case (st)
                S_IDLE: begin
                    if (s_axi_awvalid && s_axi_wvalid) begin
                        // apply the (masked) write ONCE, at accept time
                        for (int b = 0; b < 4; b++) begin
                            if (s_axi_wstrb[b]) begin
                                mem[(s_axi_awaddr - BASE) >> 2][b*8 +: 8] <=
                                    s_axi_wdata[b*8 +: 8];
                            end
                        end
                        s_axi_bvalid <= 1'b1;
                        s_axi_bresp  <= 2'b00;  // OKAY
                        st <= S_WRB;
                    end else if (s_axi_arvalid) begin
                        raddr_q <= s_axi_araddr;
                        st      <= S_RD;
                    end
                end
                S_WRB: begin
                    s_axi_bvalid <= 1'b1;  // hold B until bready
                    if (s_axi_bready) st <= S_IDLE;
                end
                S_RD: begin
                    s_axi_rvalid <= 1'b1;
                    s_axi_rdata  <= mem[(raddr_q - BASE) >> 2];
                    s_axi_rresp  <= 2'b00;  // OKAY
                    if (s_axi_rready) st <= S_IDLE;
                end
                default: st <= S_IDLE;
            endcase
        end
    end
endmodule

`default_nettype wire
