`default_nettype none
// SPDX-License-Identifier: CERN-OHL-S-2.0
// Module:      tb_bmc_daemon_packed (testbench, self-checking)
// Description: E1-RUN2 packed-deploy CAPSTONE — the BMC firmware daemon drives
//              the emri-v0.md §3.3 (v0.3) EFP run_packed flow on the REAL
//              chain, deploying BIT-PACKED production frames (frame_map
//              format) through the per-column OCC_DECODE loop (§3.1):
//
//                host BFM --AXI4--+
//                                 v
//                NEORV32 --XBUS--> eth_wb2axi --> eth_axi_xbar (2 masters)
//                                                    | 1 slave (512 B window)
//                                           emri_axi_adapter --> emri_regfile
//                                                    | OCC master    | dec_start
//                                              occ_top --fbus--> frame_decoder
//                                                    |               | cfg
//                                                    +--> column_cfg_ram
//                                                    (readback)      v
//                                                              fabric_top (2x2 CLB)
//
//              The host BFM plays ethctl --transport efp run_packed: stage
//              IMG_DIGEST/IMG_SIG/EFP_IMG_WORDS(per-column DATA count)/
//              EFP_IMG_COLS/EFP_REGION, ring EFP_CMD=run_packed, then PER
//              COLUMN: poll EFP_STATUS.state==LOAD and stream the column's
//              DATA words through OCC_WDATA while the daemon supervises
//              OCC_STATUS. The daemon (real C firmware, Ed25519 verify
//              against keyring.h) supervises VERIFY->ALLOC->BLANK(per col)->
//              LOAD(per col)->READBACK(per col)->RUNNING.
//
//              Scenario (spec §3.3):
//                1. run_packed img P (TFF, packed col0 frame from
//                   pack_tb_frames.py), 1 column @ region 0 -> RUNNING;
//                   fabric region-reset pulse (fab_usr_rst_n, same pattern as
//                   tb_bmc_axi_fabric) -> clb_out_obs[0] TOGGLES on the real
//                   fabric; READBACK CRC ok.
//                2. run_packed with tampered sig -> EFP_ERR=bad_sig, ERROR,
//                   fabric untouched.
//                3. stop region 0 -> STOPPED; the packed region is blanked
//                   PER COLUMN (occ_blank_packed path), output blanked.
//                4. run_packed img C (E1-DMO2c MULTI-COLUMN: col 0 = TFF,
//                   col 1 = const1), EFP_IMG_COLS=2 @ region 0 -> RUNNING.
//                   E1-DMO2b's v0.6 per-column window map (OCC_FRAME_ADDR =
//                   {region_id[15:12], col_id[11:8], word[7:0]}, spec §2)
//                   is what this stage exists for: it checks every column's
//                   READBACK CRC per column (OCC_EXPECT_CRC/OCC_CRC_RESULT,
//                   §3.1.1), that the daemon's per-column OCC_FRAME_ADDR
//                   writes land at region<<12 | col<<8 (0x0000 / 0x0100),
//                   that each column's config window holds its OWN frame,
//                   and that the fabric carries the DISTINGUISHABLE
//                   per-column images (col 0 TFF -> clb_out_obs[0] toggles,
//                   col 1 const1 -> clb_out_obs[8] = 1; tile index r*C+c).
//                5. run_packed img C with a tampered sig -> bad_sig: no
//                   WRITE is issued and BOTH columns keep running.
//                6. stop region 0 -> STOPPED; the 2-column region is blanked
//                   per column and both columns' outputs go 0.
//
//              The daemon's UART log is SPOT-CHECKED (containment of the key
//              lines, tb_ethctl_replay style) — not exact-matched.
// Maintainer:  BaiTian6641
// Created:     2026-09-02
// Tags:        TESTBENCH
// Plan-Ref:    ethereal-spec/control/emri-v0.md §3.3 (run_packed) + §3.1
//              (OCC_DECODE); ethereal-plan/subsystems/S05-BMC与EMRI-mFSM.md §2.3
// Notes:       Verilator --binary --timing (Makefile test-sv): a real Ed25519
//              verify is ~83M cycles on the iterative-mul NEORV32 netlist —
//              hours under iverilog, ~1 min/verify here (ADR-018 §7.5
//              exemption: cycle count, not language). Packed image
//              vectors are regenerated by gen_daemon_vectors.py --svh-packed
//              from generated/tb_frames/img_a_col0.hex (CRC16 tail dropped;
//              EFP_IMG_WORDS = 34 DATA words), plus --frame-hex-cols
//              img_c_col0.hex img_c_col1.hex for the 2-column image C
//              (DAEMON_IMGCOL_*, EFP_IMG_COLS = DAEMON_IMGCOL_NCOLS = 2).
//              UART bit time = 2 clk.
`timescale 1ns/1ps

module tb_bmc_daemon_packed;
  import emri_pkg::*;

  // -- Fabric geometry (2x2 homogeneous CLB; matches the packed golden frames)
  localparam int R = 2, C = 2, W = 12, N = 8, K = 4, EXT_IN = 18, SELW = 5;
  localparam int OBS_W = R * C * N;                 // 32
  localparam int MAX_WORDS = (R * 530 + 31) / 32;   // 34 DATA words/column (v2c)

  // -- Timing -------------------------------------------------------------------
  localparam int CLK_PERIOD_NS = 10;                // 100 MHz
  localparam int BIT_NS = 2 * CLK_PERIOD_NS;        // 20 ns/bit

  logic clk;
  logic rst_n;

  // -- DUT: bmc_core (NEORV32 + eth_wb2axi inside) = AXI master 0 ----------------
  logic        uart0_txd;
  logic        uart0_rxd;

  logic        awvalid, awready;
  logic [31:0] awaddr;
  logic [2:0]  awprot;
  logic        wvalid, wready;
  logic [31:0] wdata;
  logic [3:0]  wstrb;
  logic        bvalid, bready;
  logic [1:0]  bresp;
  logic        arvalid, arready;
  logic [31:0] araddr;
  logic [2:0]  arprot;
  logic        rvalid, rready;
  logic [31:0] rdata;
  logic [1:0]  rresp;

  bmc_core dut (
      .clk_i         (clk),
      .rst_ni        (rst_n),
      .uart0_txd_o   (uart0_txd),
      .uart0_rxd_i   (uart0_rxd),
      .m_axi_awvalid (awvalid),
      .m_axi_awready (awready),
      .m_axi_awaddr  (awaddr),
      .m_axi_awprot  (awprot),
      .m_axi_wvalid  (wvalid),
      .m_axi_wready  (wready),
      .m_axi_wdata   (wdata),
      .m_axi_wstrb   (wstrb),
      .m_axi_bvalid  (bvalid),
      .m_axi_bready  (bready),
      .m_axi_bresp   (bresp),
      .m_axi_arvalid (arvalid),
      .m_axi_arready (arready),
      .m_axi_araddr  (araddr),
      .m_axi_arprot  (arprot),
      .m_axi_rvalid  (rvalid),
      .m_axi_rready  (rready),
      .m_axi_rdata   (rdata),
      .m_axi_rresp   (rresp),
      .dbg_en_i      (1'b0),
      // SDI tied off (CS high = idle): this TB drives no EFP-SPI traffic.
      .sdi_clk_i     (1'b0),
      .sdi_csn_i     (1'b1),
      .sdi_dat_i     (1'b1),
      .sdi_dat_o     (),
      .heartbeat_o   ()
  );

  // -- Host BFM = AXI master 1 ----------------------------------------------------
  logic        h_awvalid, h_awready;
  logic [31:0] h_awaddr;
  logic        h_wvalid, h_wready;
  logic [31:0] h_wdata;
  logic        h_bvalid, h_bready;
  logic [1:0]  h_bresp;
  logic        h_arvalid, h_arready;
  logic [31:0] h_araddr;
  logic        h_rvalid, h_rready;
  logic [31:0] h_rdata;
  logic [1:0]  h_rresp;

  // -- eth_axi_xbar: 2 masters x 1 slave (+ decode-error slave) ----------------
  // EMRI window: 512 B (96 words, covers IMG_SIG @ 0x50-0x5F) @ 0x4000_2000.
  localparam int N_MST = 2, N_SLV = 1, AXI_AW = 32, AXI_DW = 32, AXI_IDW = 1;
  localparam int XIDW = AXI_IDW + 1;
  localparam logic [2*N_SLV*AXI_AW-1:0] ADDR_MAP = {32'hFFFF_FE00, 32'h4000_2000};

  logic               m_awvalid, m_awready;
  logic [AXI_AW-1:0]  m_awaddr;
  logic [XIDW-1:0]    m_awid;
  logic               m_wvalid, m_wready;
  logic [AXI_DW-1:0]  m_wdata;
  logic [AXI_DW/8-1:0] m_wstrb;
  logic               m_bvalid, m_bready;
  logic [1:0]         m_bresp;
  logic               m_arvalid, m_arready;
  logic [AXI_AW-1:0]  m_araddr;
  logic [XIDW-1:0]    m_arid;
  logic               m_rvalid, m_rready;
  logic [AXI_DW-1:0]  m_rdata;
  logic [1:0]         m_rresp;

  eth_axi_xbar #(
      .N_MST(N_MST), .N_SLV(N_SLV), .AXI_AW(AXI_AW), .AXI_DW(AXI_DW),
      .AXI_IDW(AXI_IDW), .AXI_XIDW(XIDW), .ADDR_MAP(ADDR_MAP)
  ) u_xbar (
      .clk_i(clk), .rst_ni(rst_n),
      // master 0 = BMC, master 1 = host BFM (low slice = index 0)
      .s_awvalid({h_awvalid, awvalid}), .s_awready({h_awready, awready}),
      .s_awaddr({h_awaddr, awaddr}),    .s_awid(2'b00),
      .s_wvalid({h_wvalid, wvalid}),    .s_wready({h_wready, wready}),
      .s_wdata({h_wdata, wdata}),       .s_wstrb({4'hF, wstrb}),
      .s_bvalid({h_bvalid, bvalid}),    .s_bready({h_bready, bready}),
      .s_bid(),                         .s_bresp({h_bresp, bresp}),
      .s_arvalid({h_arvalid, arvalid}), .s_arready({h_arready, arready}),
      .s_araddr({h_araddr, araddr}),    .s_arid(2'b00),
      .s_rvalid({h_rvalid, rvalid}),    .s_rready({h_rready, rready}),
      .s_rid(),                         .s_rdata({h_rdata, rdata}),
      .s_rresp({h_rresp, rresp}),
      .m_awvalid(m_awvalid), .m_awready(m_awready), .m_awaddr(m_awaddr), .m_awid(m_awid),
      .m_wvalid(m_wvalid),   .m_wready(m_wready),   .m_wdata(m_wdata),   .m_wstrb(m_wstrb),
      .m_bvalid(m_bvalid),   .m_bready(m_bready),   .m_bid({XIDW{1'b0}}), .m_bresp(m_bresp),
      .m_arvalid(m_arvalid), .m_arready(m_arready), .m_araddr(m_araddr), .m_arid(m_arid),
      .m_rvalid(m_rvalid),   .m_rready(m_rready),   .m_rid({XIDW{1'b0}}), .m_rdata(m_rdata),
      .m_rresp(m_rresp)
  );

  // -- emri_axi_adapter + emri_regfile (BMC mode, HAS_BMC=1) ----------------------
  logic        host_req, host_we, host_ready;
  logic [1:0]  host_op;
  logic [15:0] host_addr;
  logic [31:0] host_wdata, host_rdata;

  emri_axi_adapter #(
      .AXI_AW(AXI_AW), .AXI_DW(AXI_DW), .REG_BASE(32'h4000_2000), .WIN_WORDS(96)
  ) u_emri_adapter (
      .clk_i(clk), .rst_ni(rst_n),
      .s_axi_awvalid(m_awvalid), .s_axi_awready(m_awready),
      .s_axi_awaddr(m_awaddr),   .s_axi_awprot(3'b000),
      .s_axi_wvalid(m_wvalid),   .s_axi_wready(m_wready),
      .s_axi_wdata(m_wdata),     .s_axi_wstrb(m_wstrb),
      .s_axi_bvalid(m_bvalid),   .s_axi_bready(m_bready),
      .s_axi_bresp(m_bresp),
      .s_axi_arvalid(m_arvalid), .s_axi_arready(m_arready),
      .s_axi_araddr(m_araddr),   .s_axi_arprot(3'b000),
      .s_axi_rvalid(m_rvalid),   .s_axi_rready(m_rready),
      .s_axi_rdata(m_rdata),     .s_axi_rresp(m_rresp),
      .host_req_o(host_req),     .host_we_o(host_we),   .host_op_o(host_op),
      .host_addr_o(host_addr),   .host_wdata_o(host_wdata),
      .host_rdata_i(host_rdata), .host_ready_i(host_ready)
  );

  // -- EMRI -> OCC -> frame_decoder -> fabric (packed frame format, §3.1/§3.3) ---
  logic [1:0]  occ_cmd;
  logic        occ_cmd_valid, occ_cmd_ready;
  logic [15:0] occ_frame_addr, occ_word_count;
  logic [31:0] occ_wdata;
  logic        occ_wdata_valid, occ_wdata_ready;
  logic [2:0]  occ_status;
  logic        occ_crc_error;
  logic [7:0]  occ_region_locks;
  logic        occ_global_lock;
  // v0.1 R_OCC_DECODE outputs -> frame_decoder
  logic        dec_start;
  logic [7:0]  dec_col;

  // occ_top frame bus -> frame_decoder AND column_cfg_ram (readback target)
  logic [15:0] fbus_addr;
  logic [31:0] fbus_wdata;
  logic        fbus_we, fbus_re;
  logic [31:0] fbus_rdata;

  // frame_decoder -> fabric_top cfg port
  logic        dec_cfg_we;
  logic [15:0] dec_cfg_addr;
  logic [31:0] dec_cfg_data;
  logic        dec_busy, dec_done, dec_crc_error;

  // fabric observation
  logic [OBS_W-1:0]     clb_out_obs;
  logic [R*C*32-1:0]    mem_vd_obs;
  logic [R*C*48-1:0]    dsp_vp_obs;

  logic [31:0] occ_expect_crc_w;   // v0.5 §3.1.1 (OCC expected-CRC gate)
  logic [31:0] occ_crc_result_w;   // v0.5 §3.1.1 (OCC running CRC)
  emri_regfile #(
      .HAS_BMC(1'b1), .NUM_REGIONS(2), .PLATFORM_ID(32'h0)
  ) u_emri (
      .clk_i(clk), .rst_ni(rst_n),
      .host_req_i(host_req), .host_we_i(host_we), .host_op_i(host_op),
      .host_addr_i(host_addr), .host_wdata_i(host_wdata),
      .host_rdata_o(host_rdata), .host_ready_o(host_ready),
      .occ_cmd_o(occ_cmd), .occ_cmd_valid_o(occ_cmd_valid),
      .occ_cmd_ready_i(occ_cmd_ready),
      .occ_frame_addr_o(occ_frame_addr), .occ_word_count_o(occ_word_count),
      .occ_wdata_o(occ_wdata), .occ_wdata_valid_o(occ_wdata_valid),
      .occ_wdata_ready_i(occ_wdata_ready),
      .occ_status_i(occ_status), .occ_crc_error_i(occ_crc_error),
      .occ_region_locks_o(occ_region_locks), .occ_global_lock_o(occ_global_lock),
      // v0.1 R_OCC_DECODE -> frame_decoder start trigger (busy backpressured)
      .dec_start_o(dec_start), .dec_col_o(dec_col), .dec_busy_i(dec_busy),
      .occ_expect_crc_o(occ_expect_crc_w),
      .occ_crc_result_i(occ_crc_result_w)
  );

  occ_top #(.ADDR_W(16), .DATA_W(32)) u_occ (
      .clk_i(clk), .rst_ni(rst_n),
      .cmd_i(occ_cmd), .cmd_valid_i(occ_cmd_valid), .cmd_ready_o(occ_cmd_ready),
      .frame_addr_i(occ_frame_addr), .word_count_i(occ_word_count),
      .wdata_i(occ_wdata), .wdata_valid_i(occ_wdata_valid),
      .wdata_ready_o(occ_wdata_ready),
      .fbus_addr_o(fbus_addr), .fbus_wdata_o(fbus_wdata),
      .fbus_we_o(fbus_we), .fbus_re_o(fbus_re), .fbus_rdata_i(fbus_rdata),
      .status_o(occ_status), .crc_error_o(occ_crc_error),
      .region_locks_i(occ_region_locks), .global_lock_i(occ_global_lock),
      .expect_crc_i(occ_expect_crc_w),
      .crc_result_o(occ_crc_result_w)
  );

  // Readback target for the OCC READBACK CRC verify (fabric_top has no cfg read
  // port — C03 §0 sim model; same role as in tb_bmc_daemon).
  column_cfg_ram #(.ADDR_W(16), .DATA_W(32), .DEPTH(8192)) u_cfgram (
      .clk(clk), .we(fbus_we), .re(fbus_re),
      .addr(fbus_addr), .wdata(fbus_wdata), .rdata(fbus_rdata)
  );

  frame_decoder #(
      .R(R), .C(C), .W(W), .N(N), .K(K), .EXT_IN(EXT_IN), .SELW(SELW),
      .TILE_TYPE({(R * C * 8){1'b0}}),  // all CLB (homogeneous, matches img P)
      .MAX_WORDS(MAX_WORDS)
  ) u_dec (
      .clk_i(clk), .rst_ni(rst_n),
      .start_i(dec_start), .col_i(dec_col),
      .busy_o(dec_busy), .done_o(dec_done),
      .fbus_addr_i(fbus_addr), .fbus_wdata_i(fbus_wdata), .fbus_we_i(fbus_we),
      .frame_base_i(16'h0000),
      .cfg_we_o(dec_cfg_we), .cfg_addr_o(dec_cfg_addr), .cfg_data_o(dec_cfg_data),
      .crc_error_o(dec_crc_error)
  );

  // Fabric user/region reset: pulsed AFTER the WRITE decode completes so the
  // image's FFs take ff_rst_val deterministically (v2c §7.7; same pattern as
  // tb_bmc_axi_fabric — real deployments region-reset after config).
  logic fab_usr_rst_n = 1'b1;
  logic fab_rst_n;
  assign fab_rst_n = rst_n & fab_usr_rst_n;

  fabric_top #(
      .R(R), .C(C), .W(W), .N(N), .K(K), .EXT_IN(EXT_IN),
      .TILE_TYPE({(R * C * 8){1'b0}})   // all CLB
  ) u_fabric (
      .clk_i(clk), .rst_ni(fab_rst_n),   // dedicated region user-reset (pulsed post-config); NOT the shared BMC rst_n
      .cfg_we_i(dec_cfg_we), .cfg_addr_i(dec_cfg_addr), .cfg_data_i(dec_cfg_data),
      .clb_out_obs_o(clb_out_obs),
      .mem_vd_obs_o(mem_vd_obs),
      .dsp_vp_obs_o(dsp_vp_obs),
      .scan_en_i(1'b0),
      .scan_in_i(1'b0),
      .scan_out_o()
  );

  // -- Clock ---------------------------------------------------------------------
  initial clk = 1'b0;
  always #(CLK_PERIOD_NS / 2) clk = ~clk;

  // -- Firmware preload (DMEM-exec bootstrap; same backdoor as tb_bmc_daemon) ----
  initial begin
      // #1: the netlist's imem_rom has its OWN time-0 initial block filling
      // n7280 with the GHDL-conversion default image; the simulator may run it
      // AFTER a time-0 TB initial and clobber the preload. Defer past time 0
      // (the core is still in reset; reset releases at 200 ns).
      #1;
      $readmemh("generated/bmc/bmc_boot.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_imem_enabled_neorv32_imem_inst
                .imem_rom_imem_rom_inst.n7280);
      $readmemh("generated/bmc/bmc_dmem_lane0.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[0]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane1.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[1]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane2.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[2]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane3.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[3]_ram_inst .spram);
  end

  // -- Packed-image test vectors (DATA words + digest/sig + tampered sig) --------
  `include "tb_daemon_packed_vectors.svh"

  // ============================================================================
  // Concurrent UART 8N1 receiver (idle-high, start bit low, LSB first)
  // ============================================================================
  localparam int MAXB = 8192;
  bit [7:0] rxq [0:MAXB-1];
  integer   rxn = 0;   // received count

  always @(negedge uart0_txd) begin : uart_rx
      integer i;
      logic [7:0] b;
      #(BIT_NS / 2);
      if (uart0_txd === 1'b0) begin
          b = 8'h00;
          for (i = 0; i < 8; i = i + 1) begin
              #(BIT_NS);
              b[i] = uart0_txd;
          end
          #(BIT_NS);
          if (uart0_txd === 1'b1 && rxn < MAXB) begin
              rxq[rxn] = b;
              rxn = rxn + 1;
          end
      end
  end

  // ============================================================================
  // Check helpers (chk-count style of tb_ethctl_replay)
  // ============================================================================
  integer errors = 0;
  task automatic chk(input logic cond, input string msg);
      begin
          if (cond) $display("  ok: %0s", msg);
          else begin
              errors = errors + 1;
              $display("  FAIL: %0s", msg);
          end
      end
  endtask

  // Spot-check: block (bounded) until the daemon UART log CONTAINS string s.
  // (Containment, not exact-match, tb_ethctl_replay style.)
  task automatic wait_uart_contains(input string s, input string tag);
      integer to, base, j;
      logic found, m;
      begin
          to = 0;
          found = 1'b0;
          while (!found && to < 4000000) begin
              for (base = 0; base + s.len() <= rxn; base = base + 1) begin
                  m = 1'b1;
                  for (j = 0; j < s.len(); j = j + 1)
                      if (rxq[base + j] !== s[j]) m = 1'b0;
                  if (m) begin
                      found = 1'b1;
                      break;
                  end
              end
              if (!found) begin
                  #(1000);        // 1 µs poll step (verify phases are ~0.9 s)
                  to = to + 1;
              end
          end
          chk(found, tag);
      end
  endtask

  // Same spot-check, but only matches occurrences that START at/after
  // `uart_mark` (the caller sets it just before ringing a doorbell). Needed for
  // the MULTI-COLUMN deploy: "st LOAD c0" / "readback c0 ok" are printed once
  // per column, so a from-index-0 scan would match a previous column's — or an
  // earlier stage's — window instead of the one the daemon just reached.
  integer uart_mark = 0;
  task automatic wait_uart_new(input string s, input string tag);
      integer to, base, j;
      logic found, m;
      begin
          to = 0;
          found = 1'b0;
          while (!found && to < 4000000) begin
              for (base = uart_mark; base + s.len() <= rxn; base = base + 1) begin
                  m = 1'b1;
                  for (j = 0; j < s.len(); j = j + 1)
                      if (rxq[base + j] !== s[j]) m = 1'b0;
                  if (m) begin
                      found = 1'b1;
                      break;
                  end
              end
              if (!found) begin
                  #(1000);        // 1 µs poll step
                  to = to + 1;
              end
          end
          chk(found, tag);
      end
  endtask

  // ============================================================================
  // Host BFM (AXI master 1) — drive on negedge, sample handshakes on posedge
  // ============================================================================
  localparam logic [31:0] EMRI_BASE = 32'h4000_2000;

  task automatic axi_wr(input logic [31:0] a, input logic [31:0] d);
      logic aw_done, w_done;
      begin
          @(negedge clk);
          h_awaddr = a; h_awvalid = 1'b1;
          h_wdata  = d; h_wvalid  = 1'b1;
          h_bready = 1'b1;
          aw_done = 1'b0; w_done = 1'b0;
          while (!(aw_done && w_done)) begin
              @(posedge clk);
              if (h_awvalid && h_awready) aw_done = 1'b1;
              if (h_wvalid  && h_wready)  w_done  = 1'b1;
          end
          @(negedge clk);
          h_awvalid = 1'b0; h_wvalid = 1'b0;
          while (!h_bvalid) @(posedge clk);
          @(negedge clk);
          h_bready = 1'b0;
      end
  endtask

  task automatic axi_rd(input logic [31:0] a, output logic [31:0] d);
      logic ar_done, r_done;
      begin
          @(negedge clk);
          h_araddr = a; h_arvalid = 1'b1; h_rready = 1'b1;
          ar_done = 1'b0;
          while (!ar_done) begin
              @(posedge clk);
              if (h_arvalid && h_arready) ar_done = 1'b1;
          end
          @(negedge clk);
          h_arvalid = 1'b0;
          d = 32'h0; r_done = 1'b0;
          while (!r_done) begin
              @(posedge clk);
              if (h_rvalid) begin
                  d      = h_rdata;
                  r_done = 1'b1;
              end
          end
          @(negedge clk);
          h_rready = 1'b0;
      end
  endtask

  // EMRI register access (word offset -> AXI address in the window)
  task automatic host_wr(input logic [15:0] word, input logic [31:0] d);
      begin
          axi_wr(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  task automatic host_rd(input logic [15:0] word, output logic [31:0] d);
      begin
          axi_rd(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  // Poll EFP_STATUS until busy=0 (spec §3.2: host MUST wait busy=0 before the
  // next EFP_CMD write).
  task automatic host_wait_idle;
      logic [31:0] s;
      integer to;
      begin
          to = 0;
          host_rd(R_EFP_STATUS, s);
          while (s[4] && to < 100000) begin
              host_rd(R_EFP_STATUS, s);
              to = to + 1;
          end
          chk(!s[4], "EFP_STATUS.busy cleared (host may issue next command)");
      end
  endtask

  // Poll EFP_STATUS until state[3:0]==st. 1 µs poll step (an unpaced AXI poll
  // loop is ~80 ns/iter — a flat iteration bound would expire mid-VERIFY;
  // VERIFY is ~0.84 s sim, so 4M x 1 µs = 4 s of headroom).
  task automatic host_wait_state(input logic [3:0] st, input string tag);
      logic [31:0] s;
      integer to;
      begin
          to = 0;
          host_rd(R_EFP_STATUS, s);
          while (s[3:0] != st && to < 4000000) begin
              #(1000);
              host_rd(R_EFP_STATUS, s);
              to = to + 1;
          end
          chk(s[3:0] == st, tag);
      end
  endtask

  // Poll EFP_STATUS until state==st AND busy==0 (terminal of a command).
  // Same 1 µs pacing as host_wait_state.
  task automatic host_wait_terminal(input logic [3:0] st, input string tag);
      logic [31:0] s;
      integer to;
      begin
          to = 0;
          host_rd(R_EFP_STATUS, s);
          while ((s[3:0] != st || s[4]) && to < 4000000) begin
              #(1000);
              host_rd(R_EFP_STATUS, s);
              to = to + 1;
          end
          chk(s[3:0] == st && !s[4], tag);
      end
  endtask

  // ---- packed image staging (spec §3.3 staged metadata) -----------------------
  task automatic host_stage_packed(input logic tamper, input logic [31:0] region);
      integer k;
      begin
          for (k = 0; k < 8; k = k + 1)
              host_wr(R_IMG_DIGEST + 16'(k), DAEMON_IMGP_DIGEST[k]);
          for (k = 0; k < 16; k = k + 1)
              host_wr(R_IMG_SIG + 16'(k),
                      tamper ? DAEMON_IMGP_SIG_TAMPER[k] : DAEMON_IMGP_SIG[k]);
          host_wr(R_EFP_IMG_WORDS, 32'(DAEMON_IMGP_NWORDS));  // per-column DATA words
          host_wr(R_EFP_IMG_COLS, 32'd1);                      // 1 column (col 0)
          host_wr(R_EFP_REGION, region);
      end
  endtask

  // Stream the column's DATA words through OCC_WDATA (spec §3.3 step 3).
  task automatic host_stream_packed;
      integer k;
      begin
          for (k = 0; k < DAEMON_IMGP_NWORDS; k = k + 1)
              host_wr(R_OCC_WDATA, DAEMON_IMGP_WORDS[k]);
      end
  endtask

  // ---- multi-column image C staging: EFP_IMG_COLS = N (spec §3.3) -------------
  task automatic host_stage_packed_c(input logic tamper, input logic [31:0] region);
      integer k;
      begin
          for (k = 0; k < 8; k = k + 1)
              host_wr(R_IMG_DIGEST + 16'(k), DAEMON_IMGCOL_DIGEST[k]);
          for (k = 0; k < 16; k = k + 1)
              host_wr(R_IMG_SIG + 16'(k),
                      tamper ? DAEMON_IMGCOL_SIG_TAMPER[k] : DAEMON_IMGCOL_SIG[k]);
          host_wr(R_EFP_IMG_WORDS, 32'(DAEMON_IMGCOL_NWORDS));  // PER-COLUMN words
          host_wr(R_EFP_IMG_COLS, 32'(DAEMON_IMGCOL_NCOLS));    // N columns
          host_wr(R_EFP_REGION, region);
      end
  endtask

  // Stream ONE column's DATA words (spec §3.3 step 3): column c owns the
  // DAEMON_IMGCOL_WORDS slice [c*NWORDS +: NWORDS] (column 0 first).
  task automatic host_stream_packed_col(input integer c);
      integer k;
      begin
          for (k = 0; k < DAEMON_IMGCOL_NWORDS; k = k + 1)
              host_wr(R_OCC_WDATA, DAEMON_IMGCOL_WORDS[c * DAEMON_IMGCOL_NWORDS + k]);
      end
  endtask

  // ---- fabric observation (the REAL fabric outputs) ----------------------------
  task automatic observe_toggle(input integer obs_bit, input string tag);
      integer k;
      logic s0, s1;
      begin
          s0 = 1'b0; s1 = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[obs_bit] === 1'b0) s0 = 1'b1;
              if (clb_out_obs[obs_bit] === 1'b1) s1 = 1'b1;
          end
          chk(s0 && s1, tag);
      end
  endtask

  task automatic observe_const(input integer obs_bit, input logic v, input string tag);
      integer k;
      logic bad;
      begin
          bad = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[obs_bit] !== v) bad = 1'b1;
          end
          chk(!bad, tag);
      end
  endtask

  // ---- per-column deploy evidence (E1-DMO2c) -----------------------------------
  // Column frame base (spec §2, v0.6): OCC_FRAME_ADDR = {region_id[15:12],
  // col_id[11:8], word[7:0]} — the daemon composes
  // column_frame_base(region, col) = region<<12 | col<<8, giving every column
  // its own 256-word window (v0.5's 16-word col<<4 stride aliased adjacent
  // columns, E1-DMO2b).
  function automatic logic [15:0] column_frame_base(input integer region,
                                                    input integer col);
      return 16'((region << 12) | (col << 8));
  endfunction

  // Backdoor check of a deployed column's config window: the OCC writes the raw
  // packed DATA words at column_frame_base(region,col) + i, so each column's
  // window must hold exactly ITS OWN frame. Returns the mismatching-word count.
  function automatic integer cfg_window_bad(input integer region,
                                            input integer col);
      integer k, base, bad;
      begin
          bad  = 0;
          base = int'(column_frame_base(region, col));
          for (k = 0; k < DAEMON_IMGCOL_NWORDS; k = k + 1)
              if (u_cfgram.mem[base + k] !==
                  DAEMON_IMGCOL_WORDS[col * DAEMON_IMGCOL_NWORDS + k])
                  bad = bad + 1;
          cfg_window_bad = bad;
      end
  endfunction

  // Pulse the fabric region user-reset (fab_usr_rst_n, tb_bmc_axi_fabric
  // pattern): the image's FFs take ff_rst_val deterministically post-config.
  task automatic fab_region_reset;
      begin
          fab_usr_rst_n = 1'b0;
          repeat (10) @(posedge clk);
          fab_usr_rst_n = 1'b1;
          repeat (4) @(posedge clk);
      end
  endtask

  // dec_done is a 1-cycle pulse; count them — one per column BLANK and one per
  // column WRITE decode: stage 1 (1 column) = 2, stage 3 stop = 3, stage 4
  // (2 columns) = 7, stage 6 stop (2 columns) = 9.
  integer dec_done_count = 0;
  always @(posedge clk) if (dec_done) dec_done_count = dec_done_count + 1;

  // Per-column WRITE-command frame-address trace (E1-DMO2c): the daemon
  // programs OCC_FRAME_ADDR immediately before each OCC_CMD=WRITE. occ_cmd_valid
  // and occ_cmd_ready coincide for exactly one cycle (occ_top's cmd_ready is a
  // 1-cycle accept pulse) and occ_top latches frame_addr_i in that same cycle,
  // so sampling the programmed register at accept records exactly the base the
  // daemon chose for that column.
  localparam int MAX_WR_TRACE = 8;
  logic [15:0] wr_frame_addr [0:MAX_WR_TRACE-1];
  integer      wr_trace_n    = 0;
  integer      wr_trace_base = 0;   // trace index at the start of the stage
  always @(posedge clk) begin
      if (rst_n && occ_cmd_valid && occ_cmd_ready && (occ_cmd === OCC_WRITE)
          && (wr_trace_n < MAX_WR_TRACE)) begin
          wr_frame_addr[wr_trace_n] = occ_frame_addr;
          wr_trace_n = wr_trace_n + 1;
      end
  end

  task automatic wait_dec_done(input integer n, input string tag);
      integer k;
      begin
          k = 0;
          while (dec_done_count < n && k < 4000000) begin
              @(posedge clk);
              k = k + 1;
          end
          chk(dec_done_count >= n, tag);
      end
  endtask

  // ============================================================================
  // Test sequence (spec §3.3 run_packed flow)
  // ============================================================================
  logic [31:0] rd;

  initial begin : main_seq
      // idle the host BFM + UART RX
      h_awvalid = 1'b0; h_awaddr = 32'h0;
      h_wvalid  = 1'b0; h_wdata  = 32'h0;
      h_bready  = 1'b0;
      h_arvalid = 1'b0; h_araddr = 32'h0;
      h_rready  = 1'b0;
      uart0_rxd = 1'b1;

      rst_n = 1'b0;
      repeat (20) @(posedge clk);
      rst_n = 1'b1;

      // ---- 0. boot: banner + Ed25519 selftest + EMRI probe + daemon up --------
      $display("[0] boot (selftest = 2 verifies, ~1.7 s sim)");
      wait_uart_contains("bmc-fw v0.2 daemon boot\n", "boot banner");
      wait_uart_contains("ed25519 selftest OK\n", "boot Ed25519 selftest");
      wait_uart_contains("daemon ready\n", "daemon poll loop entered");

      // ---- 1. run_packed image P (TFF), 1 column, region 0 --------------------
      $display("[1] run_packed image P (packed TFF col0) — region 0, 1 column");
      host_stage_packed(1'b0, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN_PACKED});
      wait_uart_contains("cmd run_packed\n", "run_packed: doorbell accepted");
      // spec §3.3 step 3 (column 0): poll state==LOAD (the daemon arms the OCC
      // WRITE before LOAD becomes visible), then stream the DATA words.
      host_wait_state(EFP_S_LOAD, "run_packed: state==LOAD (col 0 WRITE armed)");
      wait_uart_contains("st LOAD c0\n", "run_packed: UART st LOAD c0");
      host_stream_packed();
      host_wait_terminal(EFP_S_RUNNING, "run_packed: terminal RUNNING (busy=0)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_RUNNING && rd[5] == 1'b1,
          "EFP_STATUS = RUNNING + done");
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_NONE, "EFP_ERR = none (READBACK CRC ok)");
      wait_uart_contains("st READBACK c0\n", "run_packed: UART st READBACK c0");
      wait_uart_contains("readback c0 ok\n", "run_packed: UART readback c0 ok");
      wait_uart_contains("st RUNNING r0 done\n", "run_packed: UART RUNNING");
      // the WRITE decode finished (2nd decode: BLANK #1, WRITE #2), then the
      // fabric COMPUTES: region-reset pulse + the TFF toggles on clb_out_obs[0].
      wait_dec_done(2, "run_packed: BLANK+WRITE frame_decoder decodes done");
      fab_region_reset();
      observe_toggle(0, "run_packed: clb_out_obs[0] toggles (TFF on real fabric)");

      // ---- 2. negative: tampered signature -> bad_sig, fabric untouched -------
      $display("[2] run_packed with TAMPERED signature");
      host_stage_packed(1'b1, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN_PACKED});
      wait_uart_contains("cmd run_packed\nst VERIFY\n", "tamper: accepted + VERIFY");
      wait_uart_contains("err bad_sig\nst ERROR\n", "tamper: EFP_ERR=bad_sig, ERROR");
      host_wait_idle();
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_BAD_SIG, "EFP_ERR = bad_sig (1)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_ERROR, "EFP_STATUS = ERROR");
      observe_toggle(0, "tamper: fabric untouched (P still toggling)");

      // ---- 3. stop region 0 (packed per-column blank path) ---------------------
      $display("[3] stop region 0 (packed per-column BLANK)");
      host_wr(R_EFP_REGION, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_STOP});
      wait_uart_contains("cmd stop\nst BLANK c0\nblank c0 ok\nst STOPPED r0\n",
                         "stop: per-column BLANK -> STOPPED");
      host_wait_idle();
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_STOPPED, "EFP_STATUS = STOPPED");
      wait_dec_done(3, "stop: blank frame_decoder decode done");
      fab_region_reset();
      observe_const(0, 1'b0, "stopped: clb_out_obs[0] constant 0 (column blanked)");

      // ---- 4. run_packed image C: 2 COLUMNS (E1-DMO2c) -------------------------
      // The multi-column packed deploy the v0.6 per-column window map exists
      // for: ONE signed image spanning col 0 (TFF) and col 1 (const1).
      $display("[4] run_packed image C — region 0, %0d columns (E1-DMO2c)",
               DAEMON_IMGCOL_NCOLS);
      wr_trace_base = wr_trace_n;   // trace only THIS command's WRITE commands
      uart_mark     = rxn;          // only match UART printed from here on
      host_stage_packed_c(1'b0, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN_PACKED});
      wait_uart_new("cmd run_packed\n", "run_packed C: doorbell accepted");
      wait_uart_new("alloc r0 cols 2\n", "run_packed C: ALLOC region 0, cols 2");
      // Per column the daemon arms the OCC WRITE and prints "st LOAD c<c>" only
      // AFTER that arm (spec §3.3 step 3), so the print is the per-column
      // streaming handshake — and, unlike a bare state==LOAD poll, it cannot
      // match the previous column's (or stage 1's) window.
      wait_uart_new("st LOAD c0\n", "run_packed C: col 0 WRITE armed");
      host_stream_packed_col(0);
      wait_uart_new("st LOAD c1\n", "run_packed C: col 1 WRITE armed");
      host_stream_packed_col(1);
      host_wait_terminal(EFP_S_RUNNING, "run_packed C: terminal RUNNING (busy=0)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_RUNNING && rd[5] == 1'b1,
          "run_packed C: EFP_STATUS = RUNNING + done");
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_NONE,
          "run_packed C: EFP_ERR = none (BOTH columns' READBACK CRC ok)");
      wait_uart_new("st READBACK c1\n",
                    "run_packed C: per-column READBACK loop reached col 1");
      wait_uart_new("readback c1 ok\n", "run_packed C: UART readback c1 ok");
      wait_uart_new("st RUNNING r0 done\n", "run_packed C: UART RUNNING r0 done");
      // The programmed per-column frame bases (spec §2: region<<12 | col<<8).
      $display("       per-column OCC_FRAME_ADDR: c0=%04x c1=%04x (expected %04x / %04x)",
               wr_frame_addr[wr_trace_base], wr_frame_addr[wr_trace_base + 1],
               column_frame_base(0, 0), column_frame_base(0, 1));
      chk(wr_trace_n == wr_trace_base + DAEMON_IMGCOL_NCOLS,
          "run_packed C: exactly one WRITE command per column");
      chk(wr_frame_addr[wr_trace_base]     === column_frame_base(0, 0) &&
          wr_frame_addr[wr_trace_base + 1] === column_frame_base(0, 1),
          "run_packed C: per-column OCC_FRAME_ADDR = region<<12 | col<<8");
      // Each column's config window must hold its OWN frame: the v0.5 col<<4
      // stride put col 1's words inside col 0's window (E1-DMO2b).
      chk(cfg_window_bad(0, 0) == 0,
          "run_packed C: config window 0x0000 = col 0 frame (no col 1 aliasing)");
      chk(cfg_window_bad(0, 1) == 0,
          "run_packed C: config window 0x0100 = col 1 frame");
      wait_dec_done(7, "run_packed C: BLANK c0/c1 + WRITE c0/c1 decodes done");
      fab_region_reset();
      observe_toggle(0, "run_packed C: col 0 clb_out_obs[0] toggles (TFF image)");
      observe_const(8, 1'b1, "run_packed C: col 1 clb_out_obs[8] = 1 (const1 image)");

      // ---- 5. negative: TAMPERED signature on the 2-column image --------------
      $display("[5] run_packed image C with TAMPERED signature");
      uart_mark = rxn;
      host_stage_packed_c(1'b1, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN_PACKED});
      wait_uart_new("cmd run_packed\nst VERIFY\n", "tamper C: accepted + VERIFY");
      wait_uart_new("err bad_sig\nst ERROR\n", "tamper C: EFP_ERR=bad_sig, ERROR");
      host_wait_idle();
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_BAD_SIG, "tamper C: EFP_ERR = bad_sig (1)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_ERROR, "tamper C: EFP_STATUS = ERROR");
      chk(wr_trace_n == wr_trace_base + DAEMON_IMGCOL_NCOLS,
          "tamper C: no WRITE command issued for the rejected image");
      observe_toggle(0, "tamper C: col 0 still toggling (fabric untouched)");
      observe_const(8, 1'b1, "tamper C: col 1 still constant 1 (untouched)");

      // ---- 6. stop region 0: per-column BLANK of BOTH columns -----------------
      $display("[6] stop region 0 (packed per-column BLANK, 2 columns)");
      uart_mark = rxn;
      host_wr(R_EFP_REGION, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_STOP});
      wait_uart_new("cmd stop\nst BLANK c0\nblank c0 ok\nst BLANK c1\nblank c1 ok\nst STOPPED r0\n",
                    "stop C: per-column BLANK c0+c1 -> STOPPED");
      host_wait_idle();
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_STOPPED, "stop C: EFP_STATUS = STOPPED");
      wait_dec_done(9, "stop C: both columns' blank decodes done");
      fab_region_reset();
      observe_const(0, 1'b0, "stop C: clb_out_obs[0] = 0 (col 0 blanked)");
      observe_const(8, 1'b0, "stop C: clb_out_obs[8] = 0 (col 1 blanked)");

      // ---- report ---------------------------------------------------------------
      if (errors == 0)
          $display("TEST PASSED: E1-RUN2 daemon run_packed — 1-column TFF deploy and 2-column (TFF col 0 / const1 col 1) deploy through the OCC_DECODE loop, per-column OCC_FRAME_ADDR = region<<12|col<<8, per-column READBACK CRC ok, distinct per-column fabric outputs, bad_sig rejected, per-column stop blank");
      else
          $display("TEST FAILED: %0d errors", errors);
      $finish;
  end

  // -- Watchdog -------------------------------------------------------------------
  initial begin
      // Total sim ≈ 5 verify-equivalents × ~0.84 s + 3 deploys ≈ ~5 s sim.
      repeat (15) #(1000000000);   // 15 s hard cap
      $display("TEST FAILED: watchdog timeout (rxn=%0d errors=%0d)",
               rxn, errors);
      $finish;
  end

endmodule
`default_nettype wire
