`default_nettype none
// SPDX-License-Identifier: CERN-OHL-S-2.0
// Module:      tb_bmc_daemon (testbench, self-checking)
// Description: E1-RUN2 CAPSTONE — the BMC firmware daemon drives the full
//              emri-v0.md §3.2 EFP flow on the REAL chain, with a host BFM as
//              the SECOND AXI master:
//
//                host BFM --AXI4--+
//                                 v
//                NEORV32 --XBUS--> eth_wb2axi --> eth_axi_xbar (2 masters)
//                                                    | 1 slave (512 B window)
//                                           emri_axi_adapter --> emri_regfile
//                                                    | OCC master
//                                              occ_top --fbus--> fabric_top (2x2 CLB)
//                                                            +-> column_cfg_ram
//                                                              (readback target)
//
//              The host BFM plays ethctl: stage IMG_DIGEST/IMG_SIG/
//              EFP_IMG_WORDS/EFP_REGION, ring EFP_CMD, stream OCC_WDATA while
//              the daemon is in LOAD, poll EFP_STATUS/EFP_ERR. The daemon
//              (real C firmware, Ed25519 verify against keyring.h) supervises
//              VERIFY->ALLOC->BLANK->LOAD->READBACK->RUNNING.
//
//              Scenario (spec §3.2):
//                1. run image A (TFF) auto-alloc  -> RUNNING, clb_out[0] toggles
//                  1a. MON_RECFG_COUNT.region0 == 1 (deploy notify, v0.6 §3.8)
//                  1b. CAP_DECL_IO over-declared -> EFP_ERR=11, no BLANK,
//                      no fabric mutation; the next deploy still succeeds
//                2. restart                       -> re-verify+reload, toggles
//                3. stop r0                       -> STOPPED, output blanked
//                4. run image B (const1) auto     -> RUNNING, clb_out[0] == 1
//                5. run with tampered sig         -> EFP_ERR=bad_sig, ERROR,
//                                                    fabric untouched
//                6. run on RUNNING region 0       -> EFP_ERR=region_full
//                7. abort                         -> IDLE, region blanked
//                8. forced reconfig spike         -> MON_ANOM_STATUS throttle;
//                      run to that region -> EFP_ERR=12, no ALLOC
//
//              The daemon's UART log (state transitions + errors) is
//              exact-matched byte-for-byte, in order, at every phase.
//
//              Frame format: v0 cfg-addr-addressed (fbus drives fabric_top's
//              cfg port directly AND the column_cfg_ram readback model) —
//              same format as tb_mgmt_hotswap; the bit-packed frame_decoder
//              path is covered by tb_bmc_axi_fabric. Region 0 frame base =
//              0x0000 (OCC_FRAME_ADDR.region_id[15:12]).
// Maintainer:  BaiTian6641
// Created:     2026-09-01
// Tags:        TESTBENCH
// Plan-Ref:    ethereal-spec/control/emri-v0.md §3.2 (EFP command block);
//              ethereal-plan/subsystems/S05-BMC与EMRI-mFSM.md §2.3 (E1-RUN2)
// Notes:       Simulated via Verilator --binary --timing (Makefile test-sv):
//              a real Ed25519 verify is ~83M cycles on the iterative-mul
//              NEORV32 netlist — hours under iverilog, ~1 min/verify with
//              the Verilator build (sim-only slowness; ~1.6 s @50 MHz real
//              silicon per verify). ADR-018 §7.5 iverilog constraint exempted
//              for cycle count, not language. Image/digest/signature vectors
//              are regenerated by gen_daemon_vectors.py (deterministic
//              fixed-seed key; the C keyring holds the matching public key).
//              UART bit time = 2 clk (NEORV32 reset defaults PRSC=0/BAUD=0).
`timescale 1ns/1ps

module tb_bmc_daemon;
  import emri_pkg::*;

  // -- Fabric geometry (2x2 homogeneous CLB; mirrors tb_mgmt_hotswap) ----------
  localparam int R = 2, C = 2, W = 12, N = 8, K = 4, EXT_IN = 18;
  localparam int OBS_W = R * C * N;                 // 32

  // -- Timing -------------------------------------------------------------------
  localparam int CLK_PERIOD_NS = 10;                // 100 MHz
  localparam int BIT_NS = 2 * CLK_PERIOD_NS;        // 20 ns/bit

  logic clk;
  logic rst_n;

  // -- DUT: bmc_core (NEORV32 + eth_wb2axi inside) = AXI master 0 ----------------
  logic        uart0_txd;
  logic        uart0_rxd;

  logic        awvalid, awready;
  logic [31:0] awaddr;
  logic [2:0]  awprot;
  logic        wvalid, wready;
  logic [31:0] wdata;
  logic [3:0]  wstrb;
  logic        bvalid, bready;
  logic [1:0]  bresp;
  logic        arvalid, arready;
  logic [31:0] araddr;
  logic [2:0]  arprot;
  logic        rvalid, rready;
  logic [31:0] rdata;
  logic [1:0]  rresp;

  bmc_core dut (
      .clk_i         (clk),
      .rst_ni        (rst_n),
      .uart0_txd_o   (uart0_txd),
      .uart0_rxd_i   (uart0_rxd),
      .m_axi_awvalid (awvalid),
      .m_axi_awready (awready),
      .m_axi_awaddr  (awaddr),
      .m_axi_awprot  (awprot),
      .m_axi_wvalid  (wvalid),
      .m_axi_wready  (wready),
      .m_axi_wdata   (wdata),
      .m_axi_wstrb   (wstrb),
      .m_axi_bvalid  (bvalid),
      .m_axi_bready  (bready),
      .m_axi_bresp   (bresp),
      .m_axi_arvalid (arvalid),
      .m_axi_arready (arready),
      .m_axi_araddr  (araddr),
      .m_axi_arprot  (arprot),
      .m_axi_rvalid  (rvalid),
      .m_axi_rready  (rready),
      .m_axi_rdata   (rdata),
      .m_axi_rresp   (rresp),
      .dbg_en_i      (1'b0),
      // SDI tied off (CS high = idle): this TB drives no EFP-SPI traffic.
      .sdi_clk_i     (1'b0),
      .sdi_csn_i     (1'b1),
      .sdi_dat_i     (1'b1),
      .sdi_dat_o     (),
      .heartbeat_o   ()
  );

  // -- Host BFM = AXI master 1 ----------------------------------------------------
  logic        h_awvalid, h_awready;
  logic [31:0] h_awaddr;
  logic        h_wvalid, h_wready;
  logic [31:0] h_wdata;
  logic        h_bvalid, h_bready;
  logic [1:0]  h_bresp;
  logic        h_arvalid, h_arready;
  logic [31:0] h_araddr;
  logic        h_rvalid, h_rready;
  logic [31:0] h_rdata;
  logic [1:0]  h_rresp;

  // -- eth_axi_xbar: 2 masters x 1 slave (+ decode-error slave) ----------------
  // EMRI window: 512 B (96 words, covers IMG_SIG @ 0x50-0x5F) @ 0x4000_2000.
  localparam int N_MST = 2, N_SLV = 1, AXI_AW = 32, AXI_DW = 32, AXI_IDW = 1;
  localparam int XIDW = AXI_IDW + 1;
  localparam logic [2*N_SLV*AXI_AW-1:0] ADDR_MAP = {32'hFFFF_FE00, 32'h4000_2000};

  logic               m_awvalid, m_awready;
  logic [AXI_AW-1:0]  m_awaddr;
  logic [XIDW-1:0]    m_awid;
  logic               m_wvalid, m_wready;
  logic [AXI_DW-1:0]  m_wdata;
  logic [AXI_DW/8-1:0] m_wstrb;
  logic               m_bvalid, m_bready;
  logic [1:0]         m_bresp;
  logic               m_arvalid, m_arready;
  logic [AXI_AW-1:0]  m_araddr;
  logic [XIDW-1:0]    m_arid;
  logic               m_rvalid, m_rready;
  logic [AXI_DW-1:0]  m_rdata;
  logic [1:0]         m_rresp;

  eth_axi_xbar #(
      .N_MST(N_MST), .N_SLV(N_SLV), .AXI_AW(AXI_AW), .AXI_DW(AXI_DW),
      .AXI_IDW(AXI_IDW), .AXI_XIDW(XIDW), .ADDR_MAP(ADDR_MAP)
  ) u_xbar (
      .clk_i(clk), .rst_ni(rst_n),
      // master 0 = BMC, master 1 = host BFM (low slice = index 0)
      .s_awvalid({h_awvalid, awvalid}), .s_awready({h_awready, awready}),
      .s_awaddr({h_awaddr, awaddr}),    .s_awid(2'b00),
      .s_wvalid({h_wvalid, wvalid}),    .s_wready({h_wready, wready}),
      .s_wdata({h_wdata, wdata}),       .s_wstrb({4'hF, wstrb}),
      .s_bvalid({h_bvalid, bvalid}),    .s_bready({h_bready, bready}),
      .s_bid(),                         .s_bresp({h_bresp, bresp}),
      .s_arvalid({h_arvalid, arvalid}), .s_arready({h_arready, arready}),
      .s_araddr({h_araddr, araddr}),    .s_arid(2'b00),
      .s_rvalid({h_rvalid, rvalid}),    .s_rready({h_rready, rready}),
      .s_rid(),                         .s_rdata({h_rdata, rdata}),
      .s_rresp({h_rresp, rresp}),
      .m_awvalid(m_awvalid), .m_awready(m_awready), .m_awaddr(m_awaddr), .m_awid(m_awid),
      .m_wvalid(m_wvalid),   .m_wready(m_wready),   .m_wdata(m_wdata),   .m_wstrb(m_wstrb),
      .m_bvalid(m_bvalid),   .m_bready(m_bready),   .m_bid({XIDW{1'b0}}), .m_bresp(m_bresp),
      .m_arvalid(m_arvalid), .m_arready(m_arready), .m_araddr(m_araddr), .m_arid(m_arid),
      .m_rvalid(m_rvalid),   .m_rready(m_rready),   .m_rid({XIDW{1'b0}}), .m_rdata(m_rdata),
      .m_rresp(m_rresp)
  );

  // -- emri_axi_adapter + emri_regfile (BMC mode, HAS_BMC=1) ----------------------
  logic        host_req, host_we, host_ready;
  logic [1:0]  host_op;
  logic [15:0] host_addr;
  logic [31:0] host_wdata, host_rdata;

  emri_axi_adapter #(
      .AXI_AW(AXI_AW), .AXI_DW(AXI_DW), .REG_BASE(32'h4000_2000), .WIN_WORDS(96)
  ) u_emri_adapter (
      .clk_i(clk), .rst_ni(rst_n),
      .s_axi_awvalid(m_awvalid), .s_axi_awready(m_awready),
      .s_axi_awaddr(m_awaddr),   .s_axi_awprot(3'b000),
      .s_axi_wvalid(m_wvalid),   .s_axi_wready(m_wready),
      .s_axi_wdata(m_wdata),     .s_axi_wstrb(m_wstrb),
      .s_axi_bvalid(m_bvalid),   .s_axi_bready(m_bready),
      .s_axi_bresp(m_bresp),
      .s_axi_arvalid(m_arvalid), .s_axi_arready(m_arready),
      .s_axi_araddr(m_araddr),   .s_axi_arprot(3'b000),
      .s_axi_rvalid(m_rvalid),   .s_axi_rready(m_rready),
      .s_axi_rdata(m_rdata),     .s_axi_rresp(m_rresp),
      .host_req_o(host_req),     .host_we_o(host_we),   .host_op_o(host_op),
      .host_addr_o(host_addr),   .host_wdata_o(host_wdata),
      .host_rdata_i(host_rdata), .host_ready_i(host_ready)
  );

  // -- EMRI -> OCC -> fabric (v0 cfg-addr-addressed frame format) ----------------
  logic [1:0]  occ_cmd;
  logic        occ_cmd_valid, occ_cmd_ready;
  logic [15:0] occ_frame_addr, occ_word_count;
  logic [31:0] occ_wdata;
  logic        occ_wdata_valid, occ_wdata_ready;
  logic [2:0]  occ_status;
  logic        occ_crc_error, occ_region_locked;

  logic [15:0] fbus_addr;
  logic [31:0] fbus_wdata;
  logic        fbus_we, fbus_re;
  logic [31:0] fbus_rdata;

  logic [OBS_W-1:0]     clb_out_obs;
  logic [R*C*32-1:0]    mem_vd_obs;
  logic [R*C*48-1:0]    dsp_vp_obs;

  logic [31:0] occ_expect_crc_w;   // v0.5 §3.1.1 (OCC expected-CRC gate)
  logic [31:0] occ_crc_result_w;   // v0.5 §3.1.1 (OCC running CRC)
  emri_regfile #(
      .HAS_BMC(1'b1), .NUM_REGIONS(2), .PLATFORM_ID(32'h0)
  ) u_emri (
      .clk_i(clk), .rst_ni(rst_n),
      .host_req_i(host_req), .host_we_i(host_we), .host_op_i(host_op),
      .host_addr_i(host_addr), .host_wdata_i(host_wdata),
      .host_rdata_o(host_rdata), .host_ready_o(host_ready),
      .occ_cmd_o(occ_cmd), .occ_cmd_valid_o(occ_cmd_valid),
      .occ_cmd_ready_i(occ_cmd_ready),
      .occ_frame_addr_o(occ_frame_addr), .occ_word_count_o(occ_word_count),
      .occ_wdata_o(occ_wdata), .occ_wdata_valid_o(occ_wdata_valid),
      .occ_wdata_ready_i(occ_wdata_ready),
      .occ_status_i(occ_status), .occ_crc_error_i(occ_crc_error),
      .occ_region_locked_o(occ_region_locked),
      // frame_decoder trigger unused in the v0 cfg-addr frame format
      .dec_start_o(), .dec_col_o(), .dec_busy_i(1'b0),
      .occ_expect_crc_o(occ_expect_crc_w),
      .occ_crc_result_i(occ_crc_result_w)
  );

  occ_top #(.ADDR_W(16), .DATA_W(32)) u_occ (
      .clk_i(clk), .rst_ni(rst_n),
      .cmd_i(occ_cmd), .cmd_valid_i(occ_cmd_valid), .cmd_ready_o(occ_cmd_ready),
      .frame_addr_i(occ_frame_addr), .word_count_i(occ_word_count),
      .wdata_i(occ_wdata), .wdata_valid_i(occ_wdata_valid),
      .wdata_ready_o(occ_wdata_ready),
      .fbus_addr_o(fbus_addr), .fbus_wdata_o(fbus_wdata),
      .fbus_we_o(fbus_we), .fbus_re_o(fbus_re), .fbus_rdata_i(fbus_rdata),
      .status_o(occ_status), .crc_error_o(occ_crc_error),
      .region_locked_i(occ_region_locked),
      .expect_crc_i(occ_expect_crc_w),
      .crc_result_o(occ_crc_result_w)
  );

  // Readback target for the OCC READBACK verify (fabric_top itself has no cfg
  // read port — C03 §0 sim model, same role as in tb_emri_occ_loop).
  column_cfg_ram #(.ADDR_W(16), .DATA_W(32), .DEPTH(8192)) u_cfgram (
      .clk(clk), .we(fbus_we), .re(fbus_re),
      .addr(fbus_addr), .wdata(fbus_wdata), .rdata(fbus_rdata)
  );

  fabric_top #(
      .R(R), .C(C), .W(W), .N(N), .K(K), .EXT_IN(EXT_IN)
  ) u_fabric (
      .clk_i(clk), .rst_ni(rst_n),
      .cfg_we_i(fbus_we), .cfg_addr_i(fbus_addr), .cfg_data_i(fbus_wdata),
      .clb_out_obs_o(clb_out_obs),
      .mem_vd_obs_o(mem_vd_obs),
      .dsp_vp_obs_o(dsp_vp_obs),
      .scan_en_i(1'b0),
      .scan_in_i(1'b0),
      .scan_out_o()
  );

  // -- Clock ---------------------------------------------------------------------
  initial clk = 1'b0;
  always #(CLK_PERIOD_NS / 2) clk = ~clk;

  // -- Firmware preload (DMEM-exec bootstrap; see tb_bmc_fw BOOTSTRAP note) ------
  initial begin
      // #1: the netlist's imem_rom has its OWN time-0 initial block filling
      // n7280 with the GHDL-conversion default image; the simulator may run it
      // AFTER a time-0 TB initial and clobber the preload. Defer past time 0
      // (the core is still in reset; reset releases at 200 ns).
      #1;
      $readmemh("generated/bmc/bmc_boot.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_imem_enabled_neorv32_imem_inst
                .imem_rom_imem_rom_inst.n7280);
      $readmemh("generated/bmc/bmc_dmem_lane0.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[0]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane1.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[1]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane2.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[2]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane3.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[3]_ram_inst .spram);
  end

  // -- Daemon test vectors (image words + digest/sig + tampered sig) -------------
  `include "tb_daemon_vectors.svh"

  // ============================================================================
  // Concurrent UART 8N1 receiver (idle-high, start bit low, LSB first)
  // ============================================================================
  localparam int MAXB = 8192;
  bit [7:0] rxq [0:MAXB-1];
  integer   rxn = 0;   // received count
  integer   rxr = 0;   // consumed count (expect_uart)

  always @(negedge uart0_txd) begin : uart_rx
      integer i;
      logic [7:0] b;
      #(BIT_NS / 2);
      if (uart0_txd === 1'b0) begin
          b = 8'h00;
          for (i = 0; i < 8; i = i + 1) begin
              #(BIT_NS);
              b[i] = uart0_txd;
          end
          #(BIT_NS);
          if (uart0_txd === 1'b1 && rxn < MAXB) begin
              rxq[rxn] = b;
              rxn = rxn + 1;
          end
      end
  end

  // ============================================================================
  // Check helpers
  // ============================================================================
  integer errors = 0;
  task automatic chk(input logic cond, input logic [511:0] msg);
      begin
          if (cond) $display("  ok: %0s", msg);
          else begin
              errors = errors + 1;
              $display("  FAIL: %0s", msg);
          end
      end
  endtask

  // Exact-match the next s.len() UART bytes (in order) against string s.
  // Blocks (with a generous bound) until the daemon has printed them.
  task automatic expect_uart(input string s, input logic [511:0] tag);
      integer k;
      integer to;
      integer n;
      begin
          n  = s.len();
          to = 0;
          while ((rxn - rxr) < n && to < 4000000) begin
              #(1000);            // 1 µs poll step (verify phases are ~0.9 s)
              to = to + 1;
          end
          if ((rxn - rxr) < n) begin
              errors = errors + 1;
              $display("  FAIL: %0s — UART timeout (have %0d of %0d bytes)",
                       tag, rxn - rxr, n);
          end else begin
              for (k = 0; k < n; k = k + 1) begin
                  if (rxq[rxr + k] !== s[k]) begin
                      errors = errors + 1;
                      $display("  FAIL: %0s — byte %0d = 0x%02x, expected 0x%02x",
                               tag, k, rxq[rxr + k], s[k]);
                  end
              end
              rxr = rxr + n;
              $display("  ok: %0s", tag);
          end
      end
  endtask

  // ============================================================================
  // Host BFM (AXI master 1) — drive on negedge, sample handshakes on posedge
  // ============================================================================
  localparam logic [31:0] EMRI_BASE = 32'h4000_2000;

  task automatic axi_wr(input logic [31:0] a, input logic [31:0] d);
      logic aw_done, w_done;
      begin
          @(negedge clk);
          h_awaddr = a; h_awvalid = 1'b1;
          h_wdata  = d; h_wvalid  = 1'b1;
          h_bready = 1'b1;
          aw_done = 1'b0; w_done = 1'b0;
          while (!(aw_done && w_done)) begin
              @(posedge clk);
              if (h_awvalid && h_awready) aw_done = 1'b1;
              if (h_wvalid  && h_wready)  w_done  = 1'b1;
          end
          @(negedge clk);
          h_awvalid = 1'b0; h_wvalid = 1'b0;
          while (!h_bvalid) @(posedge clk);
          @(negedge clk);
          h_bready = 1'b0;
      end
  endtask

  task automatic axi_rd(input logic [31:0] a, output logic [31:0] d);
      logic ar_done, r_done;
      begin
          @(negedge clk);
          h_araddr = a; h_arvalid = 1'b1; h_rready = 1'b1;
          ar_done = 1'b0;
          while (!ar_done) begin
              @(posedge clk);
              if (h_arvalid && h_arready) ar_done = 1'b1;
          end
          @(negedge clk);
          h_arvalid = 1'b0;
          d = 32'h0; r_done = 1'b0;
          while (!r_done) begin
              @(posedge clk);
              if (h_rvalid) begin
                  d      = h_rdata;
                  r_done = 1'b1;
              end
          end
          @(negedge clk);
          h_rready = 1'b0;
      end
  endtask

  // EMRI register access (word offset -> AXI address in the window)
  task automatic host_wr(input logic [15:0] word, input logic [31:0] d);
      begin
          axi_wr(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  task automatic host_rd(input logic [15:0] word, output logic [31:0] d);
      begin
          axi_rd(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  // Poll EFP_STATUS until busy=0 (spec §3.2: host MUST wait busy=0 before the
  // next EFP_CMD write).
  task automatic host_wait_idle;
      logic [31:0] s;
      integer to;
      begin
          to = 0;
          host_rd(R_EFP_STATUS, s);
          while (s[4] && to < 100000) begin
              host_rd(R_EFP_STATUS, s);
              to = to + 1;
          end
          chk(!s[4], "EFP_STATUS.busy cleared (host may issue next command)");
      end
  endtask

  // ---- image staging (spec §3.2 step 1) ---------------------------------------
  localparam int SEL_A        = 0;   // image A, valid signature
  localparam int SEL_B        = 1;   // image B, valid signature
  localparam int SEL_A_TAMPER = 2;   // image A, tampered signature

  task automatic host_stage(input integer sel, input logic [31:0] words,
                            input logic [31:0] region);
      integer k;
      begin
          for (k = 0; k < 8; k = k + 1)
              host_wr(R_IMG_DIGEST + 16'(k),
                      (sel == SEL_B) ? DAEMON_IMG_B_DIGEST[k]
                                     : DAEMON_IMG_A_DIGEST[k]);
          for (k = 0; k < 16; k = k + 1)
              host_wr(R_IMG_SIG + 16'(k),
                      (sel == SEL_B)        ? DAEMON_IMG_B_SIG[k]        :
                      (sel == SEL_A_TAMPER) ? DAEMON_IMG_A_SIG_TAMPER[k] :
                                              DAEMON_IMG_A_SIG[k]);
          host_wr(R_EFP_IMG_WORDS, words);
          host_wr(R_EFP_REGION, region);
      end
  endtask

  // Stream the frame words through OCC_WDATA (spec §3.2 step 5: the host
  // streams while the daemon supervises OCC_STATUS in LOAD).
  task automatic host_stream(input integer sel);
      integer k;
      begin
          if (sel == SEL_B) begin
              for (k = 0; k < DAEMON_IMG_B_NWORDS; k = k + 1)
                  host_wr(R_OCC_WDATA, DAEMON_IMG_B_WORDS[k]);
          end else begin
              for (k = 0; k < DAEMON_IMG_A_NWORDS; k = k + 1)
                  host_wr(R_OCC_WDATA, DAEMON_IMG_A_WORDS[k]);
          end
      end
  endtask

  // ---- fabric observation (the REAL fabric outputs) ----------------------------
  task automatic observe_toggle(input logic [511:0] tag);
      integer k;
      logic s0, s1;
      begin
          s0 = 1'b0; s1 = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[0] === 1'b0) s0 = 1'b1;
              if (clb_out_obs[0] === 1'b1) s1 = 1'b1;
          end
          chk(s0 && s1, tag);
      end
  endtask

  task automatic observe_const(input logic v, input logic [511:0] tag);
      integer k;
      logic bad;
      begin
          bad = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[0] !== v) bad = 1'b1;
          end
          chk(!bad, tag);
      end
  endtask

  // ============================================================================
  // Test sequence (spec §3.2 EFP flows)
  // ============================================================================
  logic [31:0] rd;
  logic [31:0] cap_shadow;   // region-1 RAM shadow snapshot for the §3.7 refusal check

  initial begin : main_seq
      // idle the host BFM + UART RX
      h_awvalid = 1'b0; h_awaddr = 32'h0;
      h_wvalid  = 1'b0; h_wdata  = 32'h0;
      h_bready  = 1'b0;
      h_arvalid = 1'b0; h_araddr = 32'h0;
      h_rready  = 1'b0;
      uart0_rxd = 1'b1;

      rst_n = 1'b0;
      repeat (20) @(posedge clk);
      rst_n = 1'b1;

      // ---- 0. boot: banner + Ed25519 selftest + EMRI probe + daemon up --------
      $display("[0] boot (selftest = 2 verifies, ~1.7 s sim)");
      expect_uart("bmc-fw v0.2 daemon boot\n", "boot banner");
      expect_uart("ed25519 selftest OK\n", "boot Ed25519 selftest");
      expect_uart("EMRI MAGIC=45544852 CAP=00000001\n", "EMRI MAGIC/CAP probe");
      // E1-IO1 (2026-09-02): main.c inits the EFP-SPI front-end after the
      // EMRI probe and before daemon_init — exact-match the new boot line so
      // the expect_uart cursor stays aligned.
      expect_uart("efp-spi ready\n", "EFP-SPI front-end initialized");
      expect_uart("daemon ready\n", "daemon poll loop entered");

      // ---- 1. run image A (TFF), auto-alloc ---------------------------------
      $display("[1] run image A (TFF) — EFP_REGION=0xFF auto-alloc");
      host_stage(SEL_A, 32'd12, 32'h0000_00FF);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN});
      expect_uart("cmd run\nst VERIFY\n", "run A: accepted + VERIFY");
      expect_uart("verify ok\nst ALLOC\nalloc r0\nst BLANK\nblank ok\nst LOAD\n",
                  "run A: VERIFY ok -> ALLOC r0 -> BLANK -> LOAD");
      host_stream(SEL_A);
      expect_uart("load ok\nst READBACK\nreadback ok\nst RUNNING r0 done\n",
                  "run A: LOAD -> READBACK -> RUNNING");
      host_wait_idle();
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_RUNNING && rd[5] == 1'b1,
          "EFP_STATUS = RUNNING + done");
      observe_toggle("run A: clb_out_obs[0] toggles (TFF on real fabric)");
      // ---- 1a. v0.6 §3.8: completed deploy notified the HW monitor ----------
      $display("[1a] MON_RECFG_COUNT after run A (region-0 deploy count)");
      host_rd(R_MON_RECFG_COUNT, rd);
      chk(rd[15:0] == 32'd1, "MON_RECFG_COUNT.region0 == 1 after one deploy");

      // ---- 1b. v0.6 §3.7 capability gate: over-declared IO -> err 11 --------
      $display("[1b] run with CAP_DECL_IO=0xFFFFFFFF (auto-alloc region 1)");
      host_stage(SEL_A, 32'd12, 32'h0000_00FF);
      cap_shadow = u_cfgram.mem[16'h1000];   // region-1 window, untouched so far
      host_wr(R_CAP_DECL_IO, 32'hFFFF_FFFF);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN});
      expect_uart("cmd run\nst VERIFY\n", "cap: accepted + VERIFY");
      expect_uart("verify ok\nst ALLOC\nalloc r1\n",
                  "cap: VERIFY ok -> ALLOC r1 (auto)");
      expect_uart("err capability_denied\nst ERROR\n",
                  "cap: EFP_ERR=capability_denied, ERROR (no BLANK)");
      host_wait_idle();
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_CAPABILITY_DENIED, "EFP_ERR = capability_denied (11)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_ERROR, "cap: EFP_STATUS = ERROR");
      host_rd(R_CAP_STATUS, rd);
      chk(rd[1] == 1'b1, "cap: CAP_STATUS.denied[1] set by the HW comparator");
      observe_toggle("cap deny: fabric untouched (image A still toggling)");
      chk(u_cfgram.mem[16'h1000] === cap_shadow,
          "cap deny: region-1 RAM shadow unchanged (no BLANK/mutation)");
      host_wr(R_CAP_DECL_IO, 32'h0000_0000);   // release the declaration
      host_rd(R_CAP_STATUS, rd);
      chk(rd[1] == 1'b0, "cap: CAP_STATUS.denied clears when undeclared");

      // ---- 2. restart (stop + re-run last staged metadata) -------------------
      // Also the "subsequent good deploy" after the §3.7 refusal: a full
      // VERIFY->ALLOC->BLANK->LOAD->READBACK->RUNNING completes, so the
      // capability denial left no stuck state.
      $display("[2] restart (re-verify + reload of image A)");
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RESTART});
      expect_uart("cmd restart\nst BLANK\nblank ok\nst VERIFY\n",
                  "restart: stop-part BLANK + VERIFY");
      expect_uart("verify ok\nst ALLOC\nalloc r0\nst BLANK\nblank ok\nst LOAD\n",
                  "restart: VERIFY ok -> ALLOC -> BLANK -> LOAD");
      host_stream(SEL_A);
      expect_uart("load ok\nst READBACK\nreadback ok\nst RUNNING r0 done\n",
                  "restart: RUNNING again");
      host_wait_idle();
      observe_toggle("restart: clb_out_obs[0] toggles again");
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_NONE,
          "recovery: EFP_ERR none after the cap refusal (no stuck state)");

      // ---- 3. stop region 0 ---------------------------------------------------
      $display("[3] stop region 0");
      host_wr(R_EFP_REGION, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_STOP});
      expect_uart("cmd stop\nst BLANK\nblank ok\nst STOPPED r0\n",
                  "stop: BLANK -> STOPPED");
      host_wait_idle();
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_STOPPED, "EFP_STATUS = STOPPED");
      observe_const(1'b0, "stopped: clb_out_obs[0] constant 0 (region blanked)");

      // ---- 4. run image B (const1), auto-alloc --------------------------------
      $display("[4] run image B (const1) — auto-alloc first free");
      host_stage(SEL_B, 32'd1, 32'h0000_00FF);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN});
      expect_uart("cmd run\nst VERIFY\n", "run B: accepted + VERIFY");
      expect_uart("verify ok\nst ALLOC\nalloc r0\nst BLANK\nblank ok\nst LOAD\n",
                  "run B: VERIFY ok -> ALLOC r0 -> BLANK -> LOAD");
      host_stream(SEL_B);
      expect_uart("load ok\nst READBACK\nreadback ok\nst RUNNING r0 done\n",
                  "run B: RUNNING");
      host_wait_idle();
      observe_const(1'b1, "run B: clb_out_obs[0] constant 1");

      // ---- 5. negative: tampered signature -> bad_sig, fabric untouched -------
      $display("[5] run with TAMPERED signature (image A metadata)");
      host_stage(SEL_A_TAMPER, 32'd12, 32'h0000_00FF);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN});
      expect_uart("cmd run\nst VERIFY\n", "tamper: accepted + VERIFY");
      expect_uart("err bad_sig\nst ERROR\n", "tamper: EFP_ERR=bad_sig, ERROR");
      host_wait_idle();
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_BAD_SIG, "EFP_ERR = bad_sig (1)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_ERROR, "EFP_STATUS = ERROR");
      observe_const(1'b1, "tamper: fabric untouched (B still constant 1)");

      // ---- 6. negative: run on RUNNING region -> region_full ------------------
      $display("[6] run on RUNNING region 0 (explicit)");
      host_stage(SEL_B, 32'd1, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN});
      expect_uart(
          "cmd run\nst VERIFY\nverify ok\nst ALLOC\nerr region_full\nst ERROR\n",
          "conflict: verify ok, ALLOC -> region_full");
      host_wait_idle();
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_REGION_FULL, "EFP_ERR = region_full (2)");
      observe_const(1'b1, "conflict: fabric still B (constant 1)");

      // ---- 7. abort -> IDLE, region blanked ------------------------------------
      $display("[7] abort");
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_ABORT});
      expect_uart("cmd abort\nst BLANK\nblank ok\nst IDLE\n",
                  "abort: best-effort BLANK -> IDLE");
      host_wait_idle();
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_IDLE, "EFP_STATUS = IDLE after abort");
      observe_const(1'b0, "abort: clb_out_obs[0] constant 0 (blanked)");
      // ---- 8. v0.6 §3.8 anomaly monitor: forced reconfig spike -> throttle --
      $display("[8] anomaly monitor: reconfig spike throttles region 0");
      host_wr(R_MON_ANOM_WINDOW, 32'd1);           // 1 tick (~4096 clk) window
      host_wr(R_MON_ANOM_THRESH, 32'h0000_0000);  // any delta > 0 spikes
      repeat (5000) @(posedge clk);               // let the window snapshot settle
      host_wr(R_MON_ANOM_STATUS, 32'hFFFF_FFFF);  // W1C: drop stale spike flags
      host_wr(R_MON_NOTIFY, 32'h0000_0001);       // one completed-deploy pulse, r0
      repeat (5000) @(posedge clk);               // cross the next monitor tick
      host_rd(R_MON_ANOM_STATUS, rd);
      chk(rd[0] == 1'b1, "anomaly: MON_ANOM_STATUS throttle[0] set");
      chk(rd[8] == 1'b1, "anomaly: MON_ANOM_STATUS flag[8] (recfg spike r0) set");
      host_rd(R_MON_RECFG_COUNT, rd);
      chk(rd[15:0] == 32'd4,
          "anomaly: MON_RECFG_COUNT.region0 == 4 (3 deploys + host notify)");
      host_rd(R_CAP_STATUS, rd);
      chk(rd[2] == 1'b1, "anomaly: CAP_STATUS.throttled[2] set");
      // A deploy to the throttled region is refused with no ALLOC at all.
      host_stage(SEL_B, 32'd1, 32'h0000_0000);
      host_wr(R_EFP_CMD, {24'h0, EFP_CMD_RUN});
      expect_uart("cmd run\nst VERIFY\n", "throttle: accepted + VERIFY");
      expect_uart("verify ok\nerr rate_limited\nst ERROR\n",
                  "throttle: EFP_ERR=rate_limited, ERROR (no ALLOC)");
      host_wait_idle();
      host_rd(R_EFP_ERR, rd);
      chk(rd[7:0] == EFP_ERR_RATE_LIMITED, "EFP_ERR = rate_limited (12)");
      host_rd(R_EFP_STATUS, rd);
      chk(rd[3:0] == EFP_S_ERROR, "throttle: EFP_STATUS = ERROR");
      observe_const(1'b0, "throttle: region 0 fabric untouched (stays blanked)");

      // ---- report ---------------------------------------------------------------
      if (errors == 0)
          $display("TEST PASSED: E1-RUN2 daemon — EFP run/restart/stop/abort on real fabric, bad_sig + region_full rejected, v0.6 cap-gate (11) + anomaly throttle (12) enforced, MON_RECFG_COUNT notified, UART log exact-matched");
      else
          $display("TEST FAILED: %0d errors", errors);
      $finish;
  end

  // -- Watchdog -------------------------------------------------------------------
  initial begin
      // Total sim ≈ 10 verify-equivalents × ~0.84 s + deploys ≈ ~9 s sim.
      repeat (25) #(1000000000);   // 25 s hard cap
      $display("TEST FAILED: watchdog timeout (rxn=%0d rxr=%0d errors=%0d)",
               rxn, rxr, errors);
      $finish;
  end

endmodule
`default_nettype wire
