`default_nettype none
// SPDX-License-Identifier: CERN-OHL-S-2.0
// Module:      tb_ethctl_replay (testbench, self-checking)
// Description: E1-RUN3 CAPSTONE — an ethctl-GENERATED EFP session script
//              (ethereal.efp-session.v0 JSON, emitted by
//              `ethctl run/stop --transport efp --emit-session`, see
//              ethereal-tools/tools/efp_client.py) replays against the REAL
//              daemon RTL chain, with the host BFM as the SECOND AXI master:
//
//                host BFM --AXI4--+
//                                 v
//                NEORV32 --XBUS--> eth_wb2axi --> eth_axi_xbar (2 masters)
//                                                    | 1 slave (512 B window)
//                                           emri_axi_adapter --> emri_regfile
//                                                    | OCC master
//                                              occ_top --fbus--> fabric_top (2x2 CLB)
//                                                            +-> column_cfg_ram
//
//              Same wiring as tb_bmc_daemon, but the host side is NOT a
//              hand-written scenario: it is a line-based replayer for the
//              machine-generated session JSON. Each op line is a compact
//              one-line JSON object keyed by the literal `{"op":"` marker;
//              all 32-bit values are "0x........" hex strings (token scan):
//                {"op":"write","addr":"0x18","data":"0x........"}
//                {"op":"read","addr":"0x16","mask":"0x3f","value":"0x26"}
//                {"op":"poll","addr":"0x16","mask":"0x10","value":"0x00"}
//                {"op":"stream","addr":"0x09","count":12,"words":["0x..",..]}
//              read/poll masks make the session self-checking; stream writes
//              each word to OCC_WDATA while the daemon is in LOAD.
//
//              Scenario (spec emri-v0.md sec 3.2):
//                1. replay session_run_a.json  (ethctl run  --region auto)
//                   -> RUNNING r0, clb_out_obs[0] toggles (TFF, real fabric)
//                2. replay session_stop_a.json (ethctl stop --region 0)
//                   -> STOPPED, clb_out_obs[0] constant 0 (region blanked)
//
//              The .eth under test is packed+signed by ethimg with the SAME
//              fixed-seed Ed25519 key as the daemon keyring.h
//              (gen_daemon_vectors.KEY_SEED), regenerated by the Makefile
//              test-sv step via `efp_client.py --emit-demo generated/ethctl`.
//              The daemon UART log is SPOT-CHECKED (substring containment of
//              the key lines: boot banner / selftest / verify ok / RUNNING /
//              STOPPED), not exact-matched — the session is machine-generated.
//
//              Frame format: v0 cfg-addr-addressed (the format the v0.2 daemon
//              consumes); the bit-packed frame_decoder path is covered by
//              tb_bmc_axi_fabric. Region 0 frame base = 0x0000.
// Maintainer:  BaiTian6641
// Created:     2026-09-01
// Tags:        TESTBENCH
// Plan-Ref:    ethereal-spec/control/emri-v0.md §3.2 (EFP command block);
//              ethereal-plan/subsystems/S08-运行时daemon与ethctl.md (E1-RUN3)
// Notes:       Verilator --binary --timing (same ADR-018 §7.5 cycle-count
//              exemption as tb_bmc_daemon: ~83M cycles per Ed25519 verify on
//              the iterative-mul NEORV32 netlist; boot selftest dominates).
//              UART bit time = 2 clk (NEORV32 reset defaults PRSC=0/BAUD=0).
`timescale 1ns/1ps

module tb_ethctl_replay;
  import emri_pkg::*;

  // -- Fabric geometry (2x2 homogeneous CLB; mirrors tb_bmc_daemon) ------------
  localparam int R = 2, C = 2, W = 12, N = 8, K = 4, EXT_IN = 18;
  localparam int OBS_W = R * C * N;                 // 32

  // -- Timing -------------------------------------------------------------------
  localparam int CLK_PERIOD_NS = 10;                // 100 MHz
  localparam int BIT_NS = 2 * CLK_PERIOD_NS;        // 20 ns/bit

  logic clk;
  logic rst_n;

  // -- DUT: bmc_core (NEORV32 + eth_wb2axi inside) = AXI master 0 ----------------
  logic        uart0_txd;
  logic        uart0_rxd;

  logic        awvalid, awready;
  logic [31:0] awaddr;
  logic [2:0]  awprot;
  logic        wvalid, wready;
  logic [31:0] wdata;
  logic [3:0]  wstrb;
  logic        bvalid, bready;
  logic [1:0]  bresp;
  logic        arvalid, arready;
  logic [31:0] araddr;
  logic [2:0]  arprot;
  logic        rvalid, rready;
  logic [31:0] rdata;
  logic [1:0]  rresp;

  bmc_core dut (
      .clk_i         (clk),
      .rst_ni        (rst_n),
      .uart0_txd_o   (uart0_txd),
      .uart0_rxd_i   (uart0_rxd),
      .m_axi_awvalid (awvalid),
      .m_axi_awready (awready),
      .m_axi_awaddr  (awaddr),
      .m_axi_awprot  (awprot),
      .m_axi_wvalid  (wvalid),
      .m_axi_wready  (wready),
      .m_axi_wdata   (wdata),
      .m_axi_wstrb   (wstrb),
      .m_axi_bvalid  (bvalid),
      .m_axi_bready  (bready),
      .m_axi_bresp   (bresp),
      .m_axi_arvalid (arvalid),
      .m_axi_arready (arready),
      .m_axi_araddr  (araddr),
      .m_axi_arprot  (arprot),
      .m_axi_rvalid  (rvalid),
      .m_axi_rready  (rready),
      .m_axi_rdata   (rdata),
      .m_axi_rresp   (rresp),
      .dbg_en_i      (1'b0),
      // SDI tied off (CS high = idle): this TB drives no EFP-SPI traffic.
      .sdi_clk_i     (1'b0),
      .sdi_csn_i     (1'b1),
      .sdi_dat_i     (1'b1),
      .sdi_dat_o     (),
      .heartbeat_o   ()
  );

  // -- Host BFM = AXI master 1 ----------------------------------------------------
  logic        h_awvalid, h_awready;
  logic [31:0] h_awaddr;
  logic        h_wvalid, h_wready;
  logic [31:0] h_wdata;
  logic        h_bvalid, h_bready;
  logic [1:0]  h_bresp;
  logic        h_arvalid, h_arready;
  logic [31:0] h_araddr;
  logic        h_rvalid, h_rready;
  logic [31:0] h_rdata;
  logic [1:0]  h_rresp;

  // -- eth_axi_xbar: 2 masters x 1 slave (+ decode-error slave) ----------------
  // EMRI window: 512 B (96 words, covers IMG_SIG @ 0x50-0x5F) @ 0x4000_2000.
  localparam int N_MST = 2, N_SLV = 1, AXI_AW = 32, AXI_DW = 32, AXI_IDW = 1;
  localparam int XIDW = AXI_IDW + 1;
  localparam logic [2*N_SLV*AXI_AW-1:0] ADDR_MAP = {32'hFFFF_FE00, 32'h4000_2000};

  logic               m_awvalid, m_awready;
  logic [AXI_AW-1:0]  m_awaddr;
  logic [XIDW-1:0]    m_awid;
  logic               m_wvalid, m_wready;
  logic [AXI_DW-1:0]  m_wdata;
  logic [AXI_DW/8-1:0] m_wstrb;
  logic               m_bvalid, m_bready;
  logic [1:0]         m_bresp;
  logic               m_arvalid, m_arready;
  logic [AXI_AW-1:0]  m_araddr;
  logic [XIDW-1:0]    m_arid;
  logic               m_rvalid, m_rready;
  logic [AXI_DW-1:0]  m_rdata;
  logic [1:0]         m_rresp;

  eth_axi_xbar #(
      .N_MST(N_MST), .N_SLV(N_SLV), .AXI_AW(AXI_AW), .AXI_DW(AXI_DW),
      .AXI_IDW(AXI_IDW), .AXI_XIDW(XIDW), .ADDR_MAP(ADDR_MAP)
  ) u_xbar (
      .clk_i(clk), .rst_ni(rst_n),
      // master 0 = BMC, master 1 = host BFM (low slice = index 0)
      .s_awvalid({h_awvalid, awvalid}), .s_awready({h_awready, awready}),
      .s_awaddr({h_awaddr, awaddr}),    .s_awid(2'b00),
      .s_wvalid({h_wvalid, wvalid}),    .s_wready({h_wready, wready}),
      .s_wdata({h_wdata, wdata}),       .s_wstrb({4'hF, wstrb}),
      .s_bvalid({h_bvalid, bvalid}),    .s_bready({h_bready, bready}),
      .s_bid(),                         .s_bresp({h_bresp, bresp}),
      .s_arvalid({h_arvalid, arvalid}), .s_arready({h_arready, arready}),
      .s_araddr({h_araddr, araddr}),    .s_arid(2'b00),
      .s_rvalid({h_rvalid, rvalid}),    .s_rready({h_rready, rready}),
      .s_rid(),                         .s_rdata({h_rdata, rdata}),
      .s_rresp({h_rresp, rresp}),
      .m_awvalid(m_awvalid), .m_awready(m_awready), .m_awaddr(m_awaddr), .m_awid(m_awid),
      .m_wvalid(m_wvalid),   .m_wready(m_wready),   .m_wdata(m_wdata),   .m_wstrb(m_wstrb),
      .m_bvalid(m_bvalid),   .m_bready(m_bready),   .m_bid({XIDW{1'b0}}), .m_bresp(m_bresp),
      .m_arvalid(m_arvalid), .m_arready(m_arready), .m_araddr(m_araddr), .m_arid(m_arid),
      .m_rvalid(m_rvalid),   .m_rready(m_rready),   .m_rid({XIDW{1'b0}}), .m_rdata(m_rdata),
      .m_rresp(m_rresp)
  );

  // -- emri_axi_adapter + emri_regfile (BMC mode, HAS_BMC=1) ----------------------
  logic        host_req, host_we, host_ready;
  logic [1:0]  host_op;
  logic [15:0] host_addr;
  logic [31:0] host_wdata, host_rdata;

  emri_axi_adapter #(
      .AXI_AW(AXI_AW), .AXI_DW(AXI_DW), .REG_BASE(32'h4000_2000), .WIN_WORDS(96)
  ) u_emri_adapter (
      .clk_i(clk), .rst_ni(rst_n),
      .s_axi_awvalid(m_awvalid), .s_axi_awready(m_awready),
      .s_axi_awaddr(m_awaddr),   .s_axi_awprot(3'b000),
      .s_axi_wvalid(m_wvalid),   .s_axi_wready(m_wready),
      .s_axi_wdata(m_wdata),     .s_axi_wstrb(m_wstrb),
      .s_axi_bvalid(m_bvalid),   .s_axi_bready(m_bready),
      .s_axi_bresp(m_bresp),
      .s_axi_arvalid(m_arvalid), .s_axi_arready(m_arready),
      .s_axi_araddr(m_araddr),   .s_axi_arprot(3'b000),
      .s_axi_rvalid(m_rvalid),   .s_axi_rready(m_rready),
      .s_axi_rdata(m_rdata),     .s_axi_rresp(m_rresp),
      .host_req_o(host_req),     .host_we_o(host_we),   .host_op_o(host_op),
      .host_addr_o(host_addr),   .host_wdata_o(host_wdata),
      .host_rdata_i(host_rdata), .host_ready_i(host_ready)
  );

  // -- EMRI -> OCC -> fabric (v0 cfg-addr-addressed frame format) ----------------
  logic [1:0]  occ_cmd;
  logic        occ_cmd_valid, occ_cmd_ready;
  logic [15:0] occ_frame_addr, occ_word_count;
  logic [31:0] occ_wdata;
  logic        occ_wdata_valid, occ_wdata_ready;
  logic [2:0]  occ_status;
  logic        occ_crc_error;
  logic [7:0]  occ_region_locks;
  logic        occ_global_lock;

  logic [15:0] fbus_addr;
  logic [31:0] fbus_wdata;
  logic        fbus_we, fbus_re;
  logic [31:0] fbus_rdata;

  logic [OBS_W-1:0]     clb_out_obs;
  logic [R*C*32-1:0]    mem_vd_obs;
  logic [R*C*48-1:0]    dsp_vp_obs;

  logic [31:0] occ_expect_crc_w;   // v0.5 §3.1.1 (OCC expected-CRC gate)
  logic [31:0] occ_crc_result_w;   // v0.5 §3.1.1 (OCC running CRC)
  emri_regfile #(
      .HAS_BMC(1'b1), .NUM_REGIONS(2), .PLATFORM_ID(32'h0)
  ) u_emri (
      .clk_i(clk), .rst_ni(rst_n),
      .host_req_i(host_req), .host_we_i(host_we), .host_op_i(host_op),
      .host_addr_i(host_addr), .host_wdata_i(host_wdata),
      .host_rdata_o(host_rdata), .host_ready_o(host_ready),
      .occ_cmd_o(occ_cmd), .occ_cmd_valid_o(occ_cmd_valid),
      .occ_cmd_ready_i(occ_cmd_ready),
      .occ_frame_addr_o(occ_frame_addr), .occ_word_count_o(occ_word_count),
      .occ_wdata_o(occ_wdata), .occ_wdata_valid_o(occ_wdata_valid),
      .occ_wdata_ready_i(occ_wdata_ready),
      .occ_status_i(occ_status), .occ_crc_error_i(occ_crc_error),
      .occ_region_locks_o(occ_region_locks), .occ_global_lock_o(occ_global_lock),
      // frame_decoder trigger unused in the v0 cfg-addr frame format
      .dec_start_o(), .dec_col_o(), .dec_busy_i(1'b0),
      .occ_expect_crc_o(occ_expect_crc_w),
      .occ_crc_result_i(occ_crc_result_w)
  );

  occ_top #(.ADDR_W(16), .DATA_W(32)) u_occ (
      .clk_i(clk), .rst_ni(rst_n),
      .cmd_i(occ_cmd), .cmd_valid_i(occ_cmd_valid), .cmd_ready_o(occ_cmd_ready),
      .frame_addr_i(occ_frame_addr), .word_count_i(occ_word_count),
      .wdata_i(occ_wdata), .wdata_valid_i(occ_wdata_valid),
      .wdata_ready_o(occ_wdata_ready),
      .fbus_addr_o(fbus_addr), .fbus_wdata_o(fbus_wdata),
      .fbus_we_o(fbus_we), .fbus_re_o(fbus_re), .fbus_rdata_i(fbus_rdata),
      .status_o(occ_status), .crc_error_o(occ_crc_error),
      .region_locks_i(occ_region_locks), .global_lock_i(occ_global_lock),
      .expect_crc_i(occ_expect_crc_w),
      .crc_result_o(occ_crc_result_w)
  );

  // Readback target for the OCC READBACK verify (fabric_top itself has no cfg
  // read port — C03 §0 sim model, same role as in tb_bmc_daemon).
  column_cfg_ram #(.ADDR_W(16), .DATA_W(32), .DEPTH(8192)) u_cfgram (
      .clk(clk), .we(fbus_we), .re(fbus_re),
      .addr(fbus_addr), .wdata(fbus_wdata), .rdata(fbus_rdata)
  );

  fabric_top #(
      .R(R), .C(C), .W(W), .N(N), .K(K), .EXT_IN(EXT_IN)
  ) u_fabric (
      .clk_i(clk), .rst_ni(rst_n),
      .cfg_we_i(fbus_we), .cfg_addr_i(fbus_addr), .cfg_data_i(fbus_wdata),
      .clb_out_obs_o(clb_out_obs),
      .mem_vd_obs_o(mem_vd_obs),
      .dsp_vp_obs_o(dsp_vp_obs),
      .scan_en_i(1'b0),
      .scan_in_i(1'b0),
      .scan_out_o()
  );

  // -- Clock ---------------------------------------------------------------------
  initial clk = 1'b0;
  always #(CLK_PERIOD_NS / 2) clk = ~clk;

  // -- Firmware preload (DMEM-exec bootstrap; see tb_bmc_fw BOOTSTRAP note) ------
  initial begin
      // #1: the netlist's imem_rom has its OWN time-0 initial block filling
      // n7280 with the GHDL-conversion default image; the simulator may run it
      // AFTER a time-0 TB initial and clobber the preload. Defer past time 0
      // (the core is still in reset; reset releases at 200 ns).
      #1;
      $readmemh("generated/bmc/bmc_boot.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_imem_enabled_neorv32_imem_inst
                .imem_rom_imem_rom_inst.n7280);
      $readmemh("generated/bmc/bmc_dmem_lane0.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[0]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane1.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[1]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane2.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[2]_ram_inst .spram);
      $readmemh("generated/bmc/bmc_dmem_lane3.hex", dut.u_core.neorv32_top_inst
                .memory_system_neorv32_dmem_enabled_neorv32_dmem_inst
                .dmem_ram_inst.\ram_gen[3]_ram_inst .spram);
  end

  // ============================================================================
  // Concurrent UART 8N1 receiver (idle-high, start bit low, LSB first)
  // ============================================================================
  localparam int MAXB = 8192;
  bit [7:0] rxq [0:MAXB-1];
  integer   rxn = 0;   // received count

  always @(negedge uart0_txd) begin : uart_rx
      integer i;
      logic [7:0] b;
      #(BIT_NS / 2);
      if (uart0_txd === 1'b0) begin
          b = 8'h00;
          for (i = 0; i < 8; i = i + 1) begin
              #(BIT_NS);
              b[i] = uart0_txd;
          end
          #(BIT_NS);
          if (uart0_txd === 1'b1 && rxn < MAXB) begin
              rxq[rxn] = b;
              rxn = rxn + 1;
          end
      end
  end

  // ============================================================================
  // Check helpers
  // ============================================================================
  integer errors = 0;
  task automatic chk(input logic cond, input string msg);
      begin
          if (cond) $display("  ok: %0s", msg);
          else begin
              errors = errors + 1;
              $display("  FAIL: %0s", msg);
          end
      end
  endtask

  // Spot-check: block (bounded) until the daemon UART log CONTAINS string s.
  // (Containment, not exact-match: the session is machine-generated, so the
  // TB checks the key daemon lines only.)
  task automatic wait_uart_contains(input string s, input string tag);
      integer to, base, j;
      logic found, m;
      begin
          to = 0;
          found = 1'b0;
          while (!found && to < 4000000) begin
              for (base = 0; base + s.len() <= rxn; base = base + 1) begin
                  m = 1'b1;
                  for (j = 0; j < s.len(); j = j + 1)
                      if (rxq[base + j] !== s[j]) m = 1'b0;
                  if (m) begin
                      found = 1'b1;
                      break;
                  end
              end
              if (!found) begin
                  #(1000);        // 1 µs poll step (verify phases are ~0.9 s)
                  to = to + 1;
              end
          end
          chk(found, tag);
      end
  endtask

  // ============================================================================
  // Host BFM (AXI master 1) — drive on negedge, sample handshakes on posedge
  // ============================================================================
  localparam logic [31:0] EMRI_BASE = 32'h4000_2000;

  task automatic axi_wr(input logic [31:0] a, input logic [31:0] d);
      logic aw_done, w_done;
      begin
          @(negedge clk);
          h_awaddr = a; h_awvalid = 1'b1;
          h_wdata  = d; h_wvalid  = 1'b1;
          h_bready = 1'b1;
          aw_done = 1'b0; w_done = 1'b0;
          while (!(aw_done && w_done)) begin
              @(posedge clk);
              if (h_awvalid && h_awready) aw_done = 1'b1;
              if (h_wvalid  && h_wready)  w_done  = 1'b1;
          end
          @(negedge clk);
          h_awvalid = 1'b0; h_wvalid = 1'b0;
          while (!h_bvalid) @(posedge clk);
          @(negedge clk);
          h_bready = 1'b0;
      end
  endtask

  task automatic axi_rd(input logic [31:0] a, output logic [31:0] d);
      logic ar_done, r_done;
      begin
          @(negedge clk);
          h_araddr = a; h_arvalid = 1'b1; h_rready = 1'b1;
          ar_done = 1'b0;
          while (!ar_done) begin
              @(posedge clk);
              if (h_arvalid && h_arready) ar_done = 1'b1;
          end
          @(negedge clk);
          h_arvalid = 1'b0;
          d = 32'h0; r_done = 1'b0;
          while (!r_done) begin
              @(posedge clk);
              if (h_rvalid) begin
                  d      = h_rdata;
                  r_done = 1'b1;
              end
          end
          @(negedge clk);
          h_rready = 1'b0;
      end
  endtask

  // EMRI register access (word offset -> AXI address in the window)
  task automatic host_wr(input logic [15:0] word, input logic [31:0] d);
      begin
          axi_wr(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  task automatic host_rd(input logic [15:0] word, output logic [31:0] d);
      begin
          axi_rd(EMRI_BASE + ({16'h0, word} << 2), d);
      end
  endtask

  // ============================================================================
  // Session-JSON replayer (ethereal.efp-session.v0; emitted by
  // `ethctl --transport efp --emit-session`). Line-based: only lines carrying
  // the literal `{"op":"` marker are ops; every 32-bit value is a "0x........"
  // hex-string token scanned in order.
  //   write:  tokens = [addr, data]
  //   read:   tokens = [addr, mask, value]   (mask!=0 -> self-check)
  //   poll:   tokens = [addr, mask, value]   (re-read until match)
  //   stream: tokens = [addr, word0..wordN]  (each word -> OCC_WDATA)
  // ============================================================================
  localparam integer POLL_TO = 30_000_000;  // polls span ~83M-cycle verifies

  task automatic replay_session(input string path, input string tag);
      integer fd, n, i, k, w, ntok, nops, to;
      string line, tok, opn;
      logic [31:0] vals [0:79];
      logic [31:0] rd;
      begin
          fd = $fopen(path, "r");
          if (fd == 0) begin
              errors = errors + 1;
              $display("  FAIL: %0s — cannot open session file %0s", tag, path);
              return;
          end
          nops = 0;
          while (!$feof(fd)) begin
              n = $fgets(line, fd);
              if (n == 0) break;
              // locate the op marker
              i = -1;
              for (k = 0; k + 7 < line.len(); k = k + 1) begin
                  if (line.substr(k, k + 6) == "{\"op\":\"") begin
                      i = k;
                      break;
                  end
              end
              if (i < 0) continue;
              // op name right after the marker ('w'rite/'r'ead/'p'oll/'s'tream)
              opn = line.substr(i + 7, i + 10);
              // scan "0x........" hex tokens after the marker
              ntok = 0;
              for (k = i; k + 11 < line.len(); k = k + 1) begin
                  if (line.substr(k, k + 2) == "\"0x") begin
                      if (ntok < 80) begin
                          tok = line.substr(k + 3, k + 10);
                          n = $sscanf(tok, "%h", vals[ntok]);
                          ntok = ntok + 1;
                      end
                      k = k + 10;
                  end
              end
              if (ntok == 0) continue;
              nops = nops + 1;
              $display("  [%0t] %0s op%0d %0s addr=0x%02x ntok=%0d",
                       $time, tag, nops, opn, vals[0], ntok);
              if (opn == "writ") begin
                  if (ntok != 2) begin
                      errors = errors + 1;
                      $display("  FAIL: %0s — write op with %0d tokens", tag, ntok);
                  end else begin
                      host_wr(vals[0][15:0], vals[1]);
                  end
              end else if (opn == "read") begin
                  if (ntok != 3) begin
                      errors = errors + 1;
                      $display("  FAIL: %0s — read op with %0d tokens", tag, ntok);
                  end else begin
                      host_rd(vals[0][15:0], rd);
                      if (vals[1] != 32'h0)
                          chk((rd & vals[1]) == vals[2],
                              $sformatf("%0s: read @0x%02x = 0x%08x (mask 0x%08x want 0x%08x)",
                                        tag, vals[0], rd, vals[1], vals[2]));
                  end
              end else if (opn == "poll") begin
                  if (ntok != 3) begin
                      errors = errors + 1;
                      $display("  FAIL: %0s — poll op with %0d tokens", tag, ntok);
                  end else begin
                      to = 0;
                      host_rd(vals[0][15:0], rd);
                      while ((rd & vals[1]) != vals[2] && to < POLL_TO) begin
                          host_rd(vals[0][15:0], rd);
                          to = to + 1;
                      end
                      chk((rd & vals[1]) == vals[2],
                          $sformatf("%0s: poll @0x%02x matched (mask 0x%08x want 0x%08x)",
                                    tag, vals[0], vals[1], vals[2]));
                  end
              end else if (opn == "stre") begin
                  for (w = 1; w < ntok; w = w + 1) begin
                      $display("  [%0t] %0s stream word %0d = 0x%08x",
                               $time, tag, w - 1, vals[w]);
                      host_wr(vals[0][15:0], vals[w]);
                  end
              end else begin
                  errors = errors + 1;
                  $display("  FAIL: %0s — unknown op '%0s'", tag, opn);
              end
          end
          $fclose(fd);
          $display("  replayed %0d ops from %0s", nops, path);
      end
  endtask

  // ---- fabric observation (the REAL fabric outputs) ----------------------------
  task automatic observe_toggle(input string tag);
      integer k;
      logic s0, s1;
      begin
          s0 = 1'b0; s1 = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[0] === 1'b0) s0 = 1'b1;
              if (clb_out_obs[0] === 1'b1) s1 = 1'b1;
          end
          chk(s0 && s1, tag);
      end
  endtask

  task automatic observe_const(input logic v, input string tag);
      integer k;
      logic bad;
      begin
          bad = 1'b0;
          for (k = 0; k < 128; k = k + 1) begin
              @(posedge clk);
              if (clb_out_obs[0] !== v) bad = 1'b1;
          end
          chk(!bad, tag);
      end
  endtask

  // ============================================================================
  // Test sequence: boot spot-checks, then replay the ethctl-generated sessions
  // ============================================================================
  initial begin : main_seq
      // idle the host BFM + UART RX
      h_awvalid = 1'b0; h_awaddr = 32'h0;
      h_wvalid  = 1'b0; h_wdata  = 32'h0;
      h_bready  = 1'b0;
      h_arvalid = 1'b0; h_araddr = 32'h0;
      h_rready  = 1'b0;
      uart0_rxd = 1'b1;

      rst_n = 1'b0;
      repeat (20) @(posedge clk);
      rst_n = 1'b1;

      // ---- 0. boot: banner + Ed25519 selftest + EMRI probe + daemon up --------
      $display("[0] boot (selftest = 2 verifies, ~1.7 s sim)");
      wait_uart_contains("bmc-fw v0.2 daemon boot\n", "boot banner");
      wait_uart_contains("ed25519 selftest OK\n", "boot Ed25519 selftest");
      wait_uart_contains("EMRI MAGIC=45544852 CAP=00000001\n", "EMRI MAGIC/CAP probe");
      wait_uart_contains("daemon ready\n", "daemon poll loop entered");

      // ---- 1. replay `ethctl run --transport efp --region auto` ---------------
      $display("[1] replay generated/ethctl/session_run_a.json (image A = TFF, 12 words)");
      replay_session("generated/ethctl/session_run_a.json", "run A");
      wait_uart_contains("verify ok\n", "run A: daemon VERIFY ok");
      wait_uart_contains("st RUNNING r0 done\n", "run A: daemon RUNNING r0 done");
      observe_toggle("run A: clb_out_obs[0] toggles (TFF on real fabric)");

      // ---- 2. replay `ethctl stop --transport efp --region 0` -----------------
      $display("[2] replay generated/ethctl/session_stop_a.json");
      replay_session("generated/ethctl/session_stop_a.json", "stop A");
      wait_uart_contains("st STOPPED r0\n", "stop A: daemon STOPPED r0");
      observe_const(1'b0, "stop A: clb_out_obs[0] constant 0 (region blanked)");

      // ---- report ---------------------------------------------------------------
      if (errors == 0)
          $display("TEST PASSED: E1-RUN3 ethctl EFP session replay — run/stop sessions drove the real daemon chain to deploy+blank, UART key lines spot-checked");
      else
          $display("TEST FAILED: %0d errors", errors);
      $finish;
  end

  // -- Watchdog -------------------------------------------------------------------
  initial begin
      // Total sim ≈ 3 verify-equivalents × ~0.84 s + deploys ≈ ~3 s sim.
      repeat (10) #(1000000000);   // 10 s hard cap
      $display("TEST FAILED: watchdog timeout (rxn=%0d errors=%0d)", rxn, errors);
      $finish;
  end

endmodule
`default_nettype wire
